### PR TITLE
core/build.gradle: set JAR dirMode and fileMode for reproducible builds

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
I haven't checked but this will most likely remove the `x` bit from the executables.

**Comment by msgilligan** [comment]
are their executables inside a JAR?

**Comment by schildbach** [comment]
> are there executables inside a JAR?

Yes, we've got `wallet-tool` and `wallet-tool.bat`.

**Comment by msgilligan** [comment]
> > are there executables inside a JAR?
> 
> 
> 
> Yes, we've got `wallet-tool` and `wallet-tool.bat`.

But they're not in a JAR, right?

**Comment by schildbach** [comment]
Ok, that's true.

**Comment by schildbach** [comment]
I folded this PR into #3270.

**Comment by schildbach** [comment]
Re-opening this, because I will merge this ahead of #3270 once we've confirmed that #3270 produces the checksums for you.

**Comment by msgilligan** [comment]
> Re-opening this, because I will merge this ahead of #3270 once we've confirmed that #3270 produces the checksums for you.

I agree this should be reviewed/merged independently.

**Comment by schildbach** [comment]
That could be archieved with

```
tasks.withType(Jar) {
    …
}
```

**Comment by schildbach** [comment]
We still might want the other attributes unchanged.

**Comment by msgilligan** [comment]
> We still might want the other attributes applied to all archives.

I pushed an update to change the `withType` to `Jar` before seeing this message. Splitting into two closures is probably a good idea. We should also probably put it in the root `build.gradle` so it applies to all subprojects.

**Comment by msgilligan** [comment]
@schildbach rebased to add dirMode and fileMode options to separate `withType(Jar)` closure.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
