### PR TITLE
Dependencies in orchid and wallettemplate

### PR DESCRIPTION
**Pull request by peacekeeper**
It seems to me the following dependencies may be missing?

In orchid:
org.easymock:easymock:3.4
org.apache.xmlrpc:xmlrpc-client:3.1.3

In wallettemplate:
com.oracle:javafx:2.2

### CODE REVIEW

**Comment by schildbach** [comment]
Generally: any changes to Orchid (also to its pom.xml) need to be accompanied with an Orchid version increase. I can help with that.

**Comment by peacekeeper** [comment]
hello thanks for looking at it, i'm sorry i may not have time to look into this further and update this pull request. maybe you want to close the pull request and instead just do any dependency updates yourself.

**Comment by schildbach** [comment]
Ok thanks. Closing this for now. I'm happy to re-open if you have time to look into my concerns.

**Comment by mikehearn** [comment]
WalletTemplate uses JavaFX 8 which is a part of Java 8 (and OpenJFX8 should be sufficient - they differ mostly in video codec support as far as a I know). So that change would be wrong.

**Pull request closed without merging**
