### PR TITLE
Java level migrations

### PR DESCRIPTION
**Pull request by schildbach**
Apply several automated Java level migrations, one per commit:

* Explicit generic type can be replaced with <>
* try finally replaceable with try with resources
* Anonymous type can be replaced with lambda
* Anonymous type has shorter lambda alternative
* Statement lambda can be replaced with expression lambda
* Lambda can be replaced with method reference
* for loop replaceable with enhanced for loop
* Identical catch branches in try statement
* Replace indexOf() with contains()

### CODE REVIEW

**Comment by schildbach** [comment]
I just noticed that I didn't have wallettemplate on my class path. I fixed that and added some refactorings.

**Review by msgilligan — APPROVED** [review]
Looks great!

**Comment by msgilligan** [comment]
-217 lines!

**Comment by schildbach** [comment]
Merged.

**Pull request merged**
