### PR TITLE
Github Actions: update builds to use Gradle 7.6

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
Any reason for this being a draft?

**Comment by schildbach** [comment]
I also wonder has the error in https://github.com/bitcoinj/bitcoinj/pull/2623 been taken care of in Gradle 7.6?

**Comment by msgilligan** [comment]
> Any reason for this being a draft?

I thought it might have a merge conflict with other PRs. I'll mark it as ready.

**Comment by msgilligan** [comment]
> I also wonder has the error in #2623 been taken care of in Gradle 7.6?
> 
> Probably yes, since the checks have all passed, but I wanted to make sure.

I thought I remembered there being some issue that was preventing us from upgrading Gradle. This was it!

I'm guessing the issue was fixed by upgrading other dependencies (perhaps EasyMock) because the rebase of PR #2623 passes checks.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
