### PR TITLE
PBKDF2SHA512Test: tests for `PBKDF2SHA512.derive()`

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by msgilligan** [comment]
Looks good! Where did the test vectors come from? It might be good to add that information to the comments with a link if available.

**Comment by schildbach** [comment]
I just added tons of more vectors. Some of them commented out because of a very large `c`.

**Comment by schildbach** [comment]
> Where did the test vectors come from? It might be good to add that information to the comments with a link if available.

The link is in the comment, even in the first version of this PR.

**Review by msgilligan — APPROVED** [review]
Approved!

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
