### PR TITLE
TransactionInput: Fix cached scriptSig gets thrown away when using se…

### PR DESCRIPTION
**Pull request by schildbach**
…tScriptSig().

It will get recreated in getScriptSig() but this can be more expensive than expected.

### CODE REVIEW

**Comment by schildbach** [comment]
Failing test: `WalletTest.completeTxPartiallySignedMarried()`
```
java.lang.AssertionError: Only one of the signatures should be missing/dummy
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.bitcoinj.core.WalletTest.completeTxPartiallySignedMarried(WalletTest.java:3321)
	at org.bitcoinj.core.WalletTest.completeTxPartiallySignedMarriedWithEmptySig(WalletTest.java:3285)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

@troggy Do you have any idea why my small change fails the test? I'm under the impression I was just fixing a bug, and suspect there might be a (previouly hidden) bug in the married wallet code.

**Comment by troggy** [comment]
No idea offhand. I'll look at this closely tomorrow

**Comment by troggy** [comment]
This one is subtle!
Empty signature should be presented as OP_0 in scriptSig, but test expects it to be empty byte array. For unclear reason it worked before your fix, while it shouldn't.
Just an idea: ``setScriptBytes`` sets scriptSig to null, therefore scriptSig was always recreated from scriptBytes (?) with 0[] instead of 0 for empty sigs — not sure how this is possible. With your fix scriptSig is being set explicitly after nullifying, so empty sigs are always 0 as they should be.

**Comment by troggy** [comment]
Proposed fix: https://github.com/schildbach/bitcoinj/pull/3

**Comment by schildbach** [comment]
I tried your fix but there are more tests that expect an empty sig. If I switch all of them, another test fails.

Also, OP_0 pushes an empty array of bytes to the stack. So `{}` actually seems correct to me. If `ScriptChunk.data` is null, this means it's not a push operation.

**Comment by schildbach** [comment]
Perhaps related: https://github.com/bitcoinj/bitcoinj/pull/1115

**Comment by natzei** [comment]
Is this PR still relevant?

**Comment by schildbach** [comment]
I guess I'll better close it.

**Pull request closed without merging**
