### PR TITLE
deprecate LazyECPoint.getEncoded and .isCompressed

### PR DESCRIPTION
**Pull request by matthewleon**
Copies the exact deprecation messages from `ECPoint`.

### CODE REVIEW

**Comment by matthewleon** [comment]
merged in https://github.com/bitcoinj/bitcoinj/commit/09c8a8e8550fd001554228cfe832304fd0ad1fa3

**Comment by schildbach** [comment]
I wonder what do we do if these methods are actually removed?

**Comment by matthewleon** [comment]
> I wonder what do we do if these methods are actually removed?

They claim they will do this.

I have been reflecting on this issue. I have some ideas I'll be exploring on a few branches. I will try to come up with something concrete.

Regardless, I do think it makes sense to deprecate these independently of whether or not they actually go ahead and get rid of them upstream.

**Comment by matthewleon** [comment]
To be a bit more specific, the `ECKey` class has a TODO somewhere in it seeking to begin tracking compression state within `ECKey` itself, rather than delegating to `ECPoint`. That should be a perfectly feasible way to do things with minimal breakage.

**Comment by schildbach** [comment]
I think we should add `@deprecated` only if we plan to remove these methods. But as far as I understand we will not remove them anytime soon because compressed state will be important for Bitcoin basically forever.

Just because the implementation used deprecated API now, that doesn't mean we need to remove the method. As you pointed out, there are alternative ways to implement the desired behaviour.

**Pull request closed without merging**
