### PR TITLE
[DRAFT] Revert "gradle.yml: update Gradle to 7.4"

### PR DESCRIPTION
**Pull request by schildbach**
This reverts commit 82d17810fd67663b54282f33089c0875e513cd4d.

### CODE REVIEW

**Comment by schildbach** [comment]
Run 1: #2309 happening on Gradle 4.10.3, not happening on any of the 6 Gradle 7.3.2. Rerunning…

**Comment by schildbach** [comment]
Run 2: All green. Rerunning…

**Comment by schildbach** [comment]
Run 4: #2309 happening with one Gradle 7.3.2, other 7.3.2 green, Gradle 4.10.3 has a read time-out on `https://plugins.gradle.org/m2/org/openjfx/javafx-plugin/0.0.10/javafx-plugin-0.0.10.pom`.

**Comment by schildbach** [comment]
I think I'd say that Gradle 7.3.2 vs 7,.3.3 vs 7.4 doesn't change much in relation to #2309.

**Comment by msgilligan** [comment]
@schildbach Can we close this one now?

**Pull request closed without merging**
