### PR TITLE
Issue 1260: the h2 prefix is prepended twice using this constructor. …

### PR DESCRIPTION
**Pull request by dcw312**
#1260 …Only prepend when calling the super constructor which happens in line 92.

### CODE REVIEW

**Comment by dcw312** [comment]
The travis-ci build seems to have failed for an independent reason. It could not obtain the orchid jar.

**Comment by schildbach** [comment]
Thanks for finding this. The connection parameters seem to be duplicated too, would you like to fix that as well?

I just fixed the build error, if you rebase your commit on current master it should be good.

**Comment by dcw312** [comment]
Regarding duplicate params, I won't have time for a few days to address that.  Please merge this request because the file name issue is a more significant bug and I'd like to prevent anyone else from duplicating the work. Thanks!

I just rebased. Incidentally, these instructions were very helpful: http://stackoverflow.com/a/7244456/205736

**Comment by schildbach** [comment]
Don't worry, I just merged (and fixed the duplicate params in the same go).

**Pull request closed without merging**
