### PR TITLE
Github Actions: Cache Gradle packages

### PR DESCRIPTION
**Pull request by msgilligan**
This should speed up the builds.

See: https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-gradle#caching-dependencies

### CODE REVIEW

**Comment by schildbach** [comment]
I plan to look at this when all the testing PRs are resolved and hopefully all tests are stable. I fear we could be introducing regressions again otherwise.

**Comment by schildbach** [comment]
I must admit I'm a bit hesitant with this. Do we have actual speed/performance problems that would warrant such a cache?

In any case, it would be useful to have this rebased to master now that the Windows checks are enabled.

**Comment by msgilligan** [comment]
> I must admit I'm a bit hesitant with this.

I was at first hesitant/skeptical about this as well, but I've used it on other projects and it seems to work well.

> Do we have actual speed/performance problems that would warrant such a cache?

Well, it takes about 5 minutes for our current "JavaCI" Github Actions workflow to run. This should probably reduce that by a minute or two (we will see shortly.) I think that savings is worthwhile -- it's nice to know sooner, rather than later if a change will succeed/fail.  (For private projects/forks it saves on cost, but given that Github is providing service to us for free...)

I think we should at least give it a try.

> In any case, it would be useful to have this rebased to master now that the Windows checks are enabled.

OK, coming up...

**Comment by msgilligan** [comment]
It looks like it speeds the "Build with Gradle" portion of the build up by about 35-40 seconds (Ubuntu/JDK 11) 2m 0s vs 2m 38s.

Remember that Gradle will still load anything that is not available in the correct version if the cache is incorrect/incomplete.

**Comment by msgilligan** [comment]
[This failure](https://github.com/bitcoinj/bitcoinj/pull/2029/checks?check_run_id=1032892689) is interesting.

```
2020-08-26T18:07:12.8307130Z org.bitcoinj.wallet.BasicKeyChainTest > bloom FAILED
2020-08-26T18:07:12.8307510Z     java.lang.AssertionError
2020-08-26T18:07:12.8311030Z         at org.junit.Assert.fail(Assert.java:87)
2020-08-26T18:07:12.8311490Z         at org.junit.Assert.assertTrue(Assert.java:42)
2020-08-26T18:07:12.8312000Z         at org.junit.Assert.assertFalse(Assert.java:65)
2020-08-26T18:07:12.8312740Z         at org.junit.Assert.assertFalse(Assert.java:75)
2020-08-26T18:07:12.8314380Z         at org.bitcoinj.wallet.BasicKeyChainTest.bloom(BasicKeyChainTest.java:261)
2020-08-26T18:07:29.5192230Z 
2020-08-26T18:07:29.5192710Z 23324 tests completed, 1 failed, 6003 skipped
```

Test source is here: https://github.com/bitcoinj/bitcoinj/blob/master/core/src/test/java/org/bitcoinj/wallet/BasicKeyChainTest.java#L248-L262

Is this caused by `ECKey key3 = new ECKey()` randomly being a "false positive"?  (the false positive rate is `0.001` in the test).

**Comment by schildbach** [comment]
For some reason, the cache always misses for the Windows builds:

```
Cache not found for input keys: Windows-gradle-c8205f7e32d1bfa84e88fcc8bcf2827d602b1828d549c46621c747dcbd9741a9, Windows-gradle
```

I reran the tests and this time they succeeded. For the bloom filter failure, see #1804.

**Comment by msgilligan** [comment]
> For some reason, the cache always misses for the Windows builds:
> 
> ```
> Cache not found for input keys: Windows-gradle-c8205f7e32d1bfa84e88fcc8bcf2827d602b1828d549c46621c747dcbd9741a9, Windows-gradle
> ```

Weird. Given that the performance difference isn't that big, let's drop this for now and take it up again later.
 
> I reran the tests and this time they succeeded. For the bloom filter failure, see #1804.

OK, glad we have an issue for that one. Good suggestions by @matthewleon

**Pull request closed without merging**
