### PR TITLE
Move org.bitcoinj.testing package to test classpath.

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by schildbach** [comment]
Merged.

**Comment by analytically** [comment]
This is breaking behaviour as this package is currently not available on Maven while BitcoinJ still is.

**Comment by schildbach** [comment]
What is the specific problem?

**Comment by analytically** [comment]
By moving these classes they now aren't packaged in the jar, while this was the case for 0.13. There is no bitcoinj-test artifact AFAICS

**Comment by schildbach** [comment]
Yes, that's intended. Why is this a problem? It's my understanding of the classes to be used in bitcoinj's tests only.

**Comment by analytically** [comment]
Ha, I have code that depended on org.bitcoinj.testing.FakeTxBuilder ...

**Comment by schildbach** [comment]
Ok, I see. We could move that back (but perhaps into the .util package) if there is a usecase besides tests for that class.

**Comment by lighthouseCash** [comment]
Hi Andreas,

Could you please move, these classes to util package, lighthouse is using them heavily.

**Pull request merged**
