### PR TITLE
Wallet: Use getConfidence(tx) not tx.getConfidence()

### PR DESCRIPTION
**Pull request by msgilligan**
This is a child of PR #3194

### CODE REVIEW

**Comment by schildbach** [comment]
Could you maybe rebase this? I'm a bit confused about what's left to merge.

**Comment by schildbach** [comment]
Ah, never mind. I managed to merge myself.

**Comment by schildbach** [comment]
However, I get this due to the new precondition check:

``` 
org.bitcoinj.core.ChainSplitTest > coinbaseDeath FAILED
    java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at org.bitcoinj.core.TransactionConfidence.setOverridingTransaction(TransactionConfidence.java:470)
        at org.bitcoinj.wallet.Wallet.killTxns(Wallet.java:2851)
        at org.bitcoinj.wallet.Wallet.reorganize(Wallet.java:5099)
        at org.bitcoinj.core.AbstractBlockChain.handleNewBestChain(AbstractBlockChain.java:856)
        at org.bitcoinj.core.AbstractBlockChain.connectBlock(AbstractBlockChain.java:673)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:553)
        at org.bitcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:401)
        at org.bitcoinj.core.ChainSplitTest.coinbaseDeath(ChainSplitTest.java:611)
```

So yes, better rebase. Sorry for the forth and back.

**Comment by msgilligan** [comment]
@schildbach Rebased, tested, and force-pushed.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
