### PR TITLE
Change data types in tables and column namechange.

### PR DESCRIPTION
**Pull request by ollekullberg**
Change data types in tables from blob to binary 

Column namechange: index -> output_index (since index is a keyword in many dbs)

### CODE REVIEW

**Comment by mikehearn** [comment]
Are there really databases that puke on a column named index? If so, why do none of our existing db impls seem to have a problem with it? I'd rather not invalidate everyone's databases in 0.13

**Comment by ollekullberg** [comment]
Ok, didn't know ppl were already using this code. I'll remove the name change then and send a new PR.

**Comment by mikehearn** [comment]
I'm not sure many people are using the MySQL DB except Kalpesh, but the other dbs are being used for sure.

**Comment by ollekullberg** [comment]
Mike, you can close this one.

**Comment by ollekullberg** [comment]
I cleaned up a bit among the backticks. They are needed around "index", so that it won't be a keyword, but I think we should be consistent to only use them there (or on all names, but that seems like a lot of work).

**Comment by mikehearn** [comment]
@kparmar1 You good with this one? It looks OK to me but I'm a non expert reviewer when it comes to MySQL

**Comment by kparmar1** [comment]
LGTM.

**Comment by kparmar1** [comment]
I've just noticed something.....

The fields transactions and txoutchanges *shouldn't* be changed to a blob in undoableblocks (leave as it). This is too small.

**Comment by kparmar1** [comment]
I think this maybe my fault as I previously mentioned that there are other fields (to consider/ look over). I actually meant these were ok, and my fatal error was to use the word blob (I meant that in a generic way - ie not binary).

**Comment by ollekullberg** [comment]
Ah, so you suspect that a txchanges field can be bigger than 64 MB (=2^16 bytes)? In that case we _should_ use mediumblob.

**Comment by ollekullberg** [comment]
Changed back into mediumblob.

**Comment by mikehearn** [comment]
@kparmar1 Looking for re-review of this since the code changed. Can you LGTM it?

**Comment by kparmar1** [comment]
LGTM.

(FYI I'm still trying to figure out why the sync on testnet is failing at times i.e when header > 80 - not releated to this of course)

**Comment by mikehearn** [comment]
OK, merged. Thanks for owning this code.

**Pull request closed without merging**
