### PR TITLE
Upgrade to SLF4J 2.0.0

### PR DESCRIPTION
**Pull request by msgilligan**
2.0.0 is a Java Module (finally!) I have been using bitcoinj with apps that have upgraded to latest alpha/beta of SLF4J for over a year now and have had no problems with the 2.0 pre-releases.

### CODE REVIEW

**Comment by schildbach** [comment]
They say [it requires Java 8](https://www.slf4j.org/news.html), without further information on wether that means language features or API. Is there any information on using slf4j on Android?

**Comment by msgilligan** [comment]
> They say [it requires Java 8](https://www.slf4j.org/news.html), without further information on wether that means language features or API. Is there any information on using slf4j on Android?

It adds a new "fluent" API that adds lambdas, but I have not used this as the existing API is preserved. I don't know about Android and I haven't tried it there. You should be able to just bump the dependency version in Bitcoin Wallet and try it.

This Q/A in the FAQ provides some additional information: https://www.slf4j.org/faq.html#changesInVersion200

**Comment by schildbach** [comment]
Sure, but I think we need some written "promise".

I tried updating and am getting the following crash, independent of the Android version:

```
08-27 21:35:24.005  9492  9492 E AndroidRuntime: java.lang.RuntimeException: Unable to create application de.schildbach.wallet.WalletApplication: java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.ActivityThread.-wrap1(Unknown Source:0)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: Caused by: java.lang.ClassCastException: org.slf4j.helpers.NOPLoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at de.schildbach.wallet.Logging.init(Logging.java:51)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at de.schildbach.wallet.WalletApplication.onCreate(WalletApplication.java:93)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
08-27 21:35:24.005  9492  9492 E AndroidRuntime: 	... 8 more
08-27 21:35:24.015  3460  6281 W ActivityManager:   Force finishing activity de.schildbach.wallet_test/de.schildbach.wallet.WalletActivity
```

Seems like logback-android needs to adapted to some change of slf4j 2.0.

**Comment by schildbach** [comment]
https://www.slf4j.org/faq.html#requirements states:

> As of version 2.0.0, SLF4J requires JDK 8 or later. Version 1.7.0 requires JDK 1.5 or later.

**Comment by msgilligan** [comment]
We can put this one on the "back-burner" for a little while. It is easy enough for users of **bitcoinj** to bump the version of this library to 2.0.x using Gradle (or Maven I assume) and that seems to work everywhere I've tried it (I haven't tried Android.)

**Comment by msgilligan** [comment]
> Seems like logback-android needs to adapted to some change of slf4j 2.0.

It might be that your Android build is filtering out a resource in `META-INF/services` that defines a Service for the Service Locator mechanism and this is causing the facade to not find the back-end implementation.

**Comment by schildbach** [comment]
Yes, let's revisit this later, possibly for 0.18.

In the meantime, I've asked this question in slf4j's discussion forum: https://github.com/qos-ch/slf4j/discussions/301

**Comment by schildbach** [comment]
There is a PR to logback-android to update it to be compatible to slf4j 2.x: https://github.com/tony19/logback-android/pull/247

The maintainer of logback-android plans to release a new major version once that's merged: https://github.com/tony19/logback-android/milestone/21

I will then do compatibility testing with several Android versions. If that doesn't uncover problems, I'm ok with merging this.

**Comment by msgilligan** [comment]
Rebased, updated to SLF4J 2.0.6, and force-pushed.

**Comment by schildbach** [comment]
I'm currently waiting for a fixed version of `logback-android` before merging this.

**Comment by msgilligan** [comment]
> I'm currently waiting for a fixed version of logback-android ...

I know, I just resolved the merge conflicts and bumped to the latest 2.0.x so this PR is more likely to be ready when that happens.

**Comment by schildbach** [comment]
Hmm, looks like we can close this?

**Pull request closed without merging**
