### PR TITLE
ByteUtils: add `readUint64()` helper to read unsigned 64-bit values

### PR DESCRIPTION
**Pull request by schildbach**
This is a followup PR to #2866.

### CODE REVIEW

**Comment by schildbach** [comment]
I should note I've added the method to `ByteUtils` because all the other readers are there. If we decide to move them to somewhere else first, or structure them a different way, I'm happy to rebase and adapt this PR.

**Review by msgilligan — CHANGES_REQUESTED** [review]
I would use an (unsigned) `long` here. If you look at all the use cases they're converting to a `long` (at some point) anyway.  "Services" is stored in `PeerAddress` as a `BigInteger` but is converted to a long in many places. This value doesn't seem to be used arithmetically, so I think it is simpler to use a `long` for it.

**Comment by schildbach** [comment]
> I would use an (unsigned) `long` here. If you look at all the use cases they're converting to a `long` (at some point) anyway. "Services" is stored in `PeerAddress` as a `BigInteger` but is converted to a long in many places. This value doesn't seem to be used arithmetically, so I think it is simpler to use a `long` for it.

I get what you're saying, but how do you know this assumption is true now and in future? I really don't want to encourage consumers to store unsigned long in a Java long. If they want to do that, they can always use `.longValue()`.

The service bits case is a valid point. Maybe we should create a custom class for that, or use something like a bit-field class – not aware of the available options in the Java API atm. Such a class would then offer read and write helpers that don't take the detour via `BigInteger`.

**Comment by schildbach** [comment]
I will close this in favor of #2874, #2871 and #2872. If those are merged, the helper is rendered unnecessary.

**Comment by schildbach** [comment]
Closing.

**Pull request closed without merging**
