### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by C-Otto**
A variety of cleanup efforts

### CODE REVIEW

**Comment by schildbach** [comment]
I cherry-picked some of your commits. Can you rebase the rest on current master?

**Comment by C-Otto** [comment]
Done.

**Comment by C-Otto** [comment]
Indeed, the static initializers depend on each other, which explains the bug you noticed. I have an idea how to solve this, I'll remove the commit from this PR in the mean time.

**Comment by schildbach** [comment]
I just merged some more commits from this PR.

**Comment by C-Otto** [comment]
The remaining commits are now in #1021

**Pull request closed without merging**
