### PR TITLE
RejectMessage: make immutable

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Review by msgilligan — CHANGES_REQUESTED** [review]
Rather than renaming the fields to match the (deprecated) getters, I would rename the accessors to (mostly) match the existing fields:
* `.message()`
* `.code()`
* `.reason()`
* `.rejectedHash()`

Once this is merged, I'll create a PR to eliminate the `@Nullable` field by using the ADT pattern.

**Comment by schildbach** [comment]
Actually I tried to move the field names a bit closer to the actual spec, which imho has not very well though out names:

https://github.com/bitcoin/bips/blob/master/bip-0061.mediawiki

**Comment by schildbach** [comment]
I think just `message` is misleading. At quick glance, it can be mistaken as a textual description of the reject code – similar to Java exception messages. We could rename it to "response-to-msg" (as per the spec), but that seems inwieldy. Which is why I've stuck to the `rejectedMessage` from the getter.

**Comment by msgilligan** [comment]
> `message` is misleading … can be mistaken as a textual description of the reject code – similar to Java exception messages.

Good point.

> `rejectedMessage`

Yes, that is probably the best choice, then.

Maybe:

* `.rejectedMessage()`
* `.code()`
* `.reason()`
* `.rejectedHash()`

?

**Comment by schildbach** [comment]
Ok, I put a commit on top:

* rename rejectCode → code
* rename rejectReason → reason

**Comment by schildbach** [comment]
Are you ok with `rejectedObjectHash` (rather than `rejectedHash`)? Makes it more clear what hash we're talking about.

(I can imagine if you do the subclass refactoring this will be renamed to `rejectedTransactionHash` and `rejectedBlockHash` anyway.)

**Comment by msgilligan** [comment]
> Are you ok with `rejectedObjectHash` 

What about `rejectedMessageHash()`?

**Comment by schildbach** [comment]
Ok, renamed to `rejectedMessageHash` and merged.

**Comment by msgilligan** [comment]
@schildbach points out that these messages are mostly gone, see: https://github.com/bitcoin/bitcoin/pull/15437

**Pull request closed without merging**
