### PR TITLE
README: Add Github Actions and Travis CI chicklet badges

### PR DESCRIPTION
**Pull request by msgilligan**
Badges? We got your stinkin’ badges!

### CODE REVIEW

**Comment by msgilligan** [comment]
@schildbach Rebased and "passing" (README only change haha)

**Comment by schildbach** [comment]
Thanks for updating this. I'd like to take the opportunity and ask if we actully want/need these badges? It causes each visitor to our repo to leak their browser fingerprint to all the sites. And personally I've never cared much about the projects status in the form of badges – email notifications to the participants of a change have worked quite well I'd say. What do you think?

**Comment by msgilligan** [comment]
I like the badges. I missed them when I was working on PRs yesterday, that's why I added them. I like to be able to quickly see that all CI builds are working and to be reminded which CI services are being used by each project I work on.

Personally, I'm not concerned about leaking my browser fingerprint to the CI SaaS companies. In  general, they're not in the business of harvesting data (though I'm sure they're monitoring the data for the purpose of optimizing their software and for marketing, as well.) It's a good point to bring up, but it's just not very high on my personal list of security concerns. Is this a serious, show-stopper concern for you? Do you think it will really impact visitors or contributors to the project?

For people who are checking out the project page for the first time, I think it's important to have them there. When I see a site with CI badges I know it is (all else being equal) a higher-quality project. If they're green that's a good sign, too.

I also spent some time yesterday thinking if we need all 3 services and I think we benefit from all of them:

1. Github Actions: Integration with Github is nice, easy provision of macOS and Windows, latest Gradle always built-in, other useful tools (e.g. installers required by `jpackage`) built-in to their images.
2. GitLab CI: Built using standard docker images, so gives us a tested and verified recipe for building locally. Also allows us to run the same build locally using gitlab-runner. Tests with older/minimum version of Gradle, though I think we might want to change this and rely on TravisCI for that. (I'll bring this up elsewhere.)
3. TravisCI: Easy support for matrix testing, tests with older/minimum versions of Gradle.

**Comment by schildbach** [comment]
Ok, fair enough. I merged this.

I think TravisCI can be removed at some point, it feels redundant. But there is no hurry.

**Comment by msgilligan** [comment]
> When I see a site with CI badges I know it is (all else being equal) a higher-quality project. If they're green that's a good sign, too.

@schildbach So you merged this PR and the Gitlab badge now says "failing". I think it's just a random failure. When you get a chance can you click the "restart" button the Gitlab job?

https://gitlab.com/bitcoinj/bitcoinj/-/jobs/527357817

**Pull request closed without merging**
