### PR TITLE
MonetaryFormat.satoshisToDecimal: encapsulate decimal conversion

### PR DESCRIPTION
**Pull request by msgilligan**
This is a reasonable standalone refactoring, and is being made in preparation for migration away from a  dependency on Guava's LongMath.

### CODE REVIEW

**Comment by schildbach** [comment]
This adds a good chunk of code, and I wonder how does it aid to migrate away from "LongMath"?

**Comment by msgilligan** [comment]
> This adds a good chunk of code, and I wonder how does it aid to migrate away from "LongMath"?

If you don't count the comments and the `DecimalNumber` wrapper class for the return value, it doesn't really add any code.  (Note: that the `DecimalNumber` wrapper in the future would be a `record` class)

It aids in migrating away from `LongMath` because it wraps 3 usages of `LongMath` in a single function. So instead of providing replacements for `LongMath.divide` and `LongMath.checkedPow` we can use an alternative method of producing `DecimalNumber`.  Two possibilities for this are using `BigInteger` and/or `BigDecimal` or possibly some methods in the `Coin` class.

Placing this functionality in a dedicated method makes it easier to reason about and makes it more clear which variables are temporary variables.

**Comment by msgilligan** [comment]
With #2817 about to be merged, I think addressing this PR (and any related follow-up) is the last thing we have to do to remove all non-deprecated usages of Guava from `o.b.base`.

**Comment by schildbach** [comment]
I now understand where this PR is going. Merging…

**Comment by msgilligan** [comment]
Merged. (and since then, improved.)

**Pull request closed without merging**
