### PR TITLE
TransactionTest: rewrite testHashForSignatureThreadSafety() to use an executor

### PR DESCRIPTION
**Pull request by schildbach**
This will actually fail the test if an assert in the worker threads fails.
Previously, it was just printing the exception to standard output.

### CODE REVIEW

**Comment by schildbach** [comment]
@msgilligan I'm interested in your advice. Is this the way we juggle with threads on Java 8?

**Comment by msgilligan** [comment]
> Is this the way we juggle with threads on Java 8?

I'm pretty sure there is a cleaner implementation for typical use. In this case we are deliberately trying to find thread safety issues and I'll need to think about it a little more carefully.

I'll try to code something up over the next few days.

**Comment by schildbach** [comment]
Thanks for looking into this. Actually don't worry about coding this up – I'd do it. I just wanted to make sure I'm using the desired API here.

**Comment by msgilligan** [comment]
Please see PR #2291 which uses Streams and `CompletableFuture`.

**Pull request merged**
