### PR TITLE
Added SPVBlockStore indexing

### PR DESCRIPTION
**Pull request by fireuse**
I have added indexing to SPVBlockStore so it will be faster when getting blocks.

### CODE REVIEW

**Comment by schildbach** [comment]
Do you have a specific usecase in mind for which this is important?

I'm a bit reluctant about changes to SPVBlockStore since so many walles depend on it.

**Comment by fireuse** [comment]
Yes, when you need to access block that isn't cached. In my solution i don't need to iterate over all block store to find block, so it is faster.

**Comment by schildbach** [comment]
Yes, sure, but when is this necessary?

**Comment by fireuse** [comment]
For example in blockchains explorers, or when looking at old transactions in wallet.

**Comment by schildbach** [comment]
SPVBlockStore is not suitable for these usecases! It only covers the last weeks worth of blocks, never an entire block chain. For block explorer type scenarios, I suggest using a real database (e.g. PostgresFullPrunedBlockStore).

**Comment by fireuse** [comment]
But even if you access block from yesterday, it will be faster because that block isn't cached. For example when you are getting list of yesterday's transactions it will be faster.

**Comment by schildbach** [comment]
SPVBlockStore is simply not designed for historic queries, and certainly not on a transaction basis. SPVBlockStore is designed for the needs of SPV (simply payment verification) implementations. And SPV only goes back in history if a rollback occurs. For that event, the current caching is fine.

**Comment by fireuse** [comment]
But assume we are opening wallet and printing last 20 transactions, transactions will be in uncached blocks(because we just opened wallet). In old version this app would load a few seconds longer.
And i am not removing current caching but i am extending it.

**Comment by schildbach** [comment]
What wallet implementation are you talking about? org.bitcoinj.wallet.Wallet?

Why should a wallet access the block store? Wallets usually store their relevant transactions and/or their relevant UTXOs themselves. If they would rely on SPVBlockStore, they would not be able to access transactions older than a few weeks.

**Comment by fireuse** [comment]
Ok so I am closing this pull request.

**Pull request closed without merging**
