### PR TITLE
Rename getChangeAddress() to currentChangeAddress()

### PR DESCRIPTION
**Pull request by oscarguindzberg**
To match currentReceiveAddress()

### CODE REVIEW

**Comment by schildbach** [comment]
LGTM. It would be interesting to know why the comment thinks the method will go away in future.

**Comment by mikehearn** [comment]
LGTM

The method was scheduled for destruction because we knew that we'd do rotating addresses at some point :)

**Comment by schildbach** [comment]
Merged, thanks. Of course the real question was: maybe it's time to remove the method entirely?

**Comment by mikehearn** [comment]
Making it a deprecated alias seems OK to me.

**Pull request merged**
