### PR TITLE
Use maximum money value from network parameters

### PR DESCRIPTION
**Pull request by rnicoll**
Enables support for altcoins with different maximum money values.

### CODE REVIEW

**Comment by schildbach** [comment]
That's a pretty hefty change just for getting rid of the MAX_COINS direct access in Coin.

I'm not sure why I put the range change into Coin at all. Coin is meant to be chain agnostic. The only thing it should be concerned about is not to overflow its own calculations. I'm pretty sure errors like trying to send more coins than MAX_COINS are caught in the higher layers of Bitcoin (-:

So what do you think about removing the check entirely? That should get rid of almost all your changes, no?

**Comment by rnicoll** [comment]
Sounds good, will replace with a simpler patch later this week

**Comment by schildbach** [comment]
I just opened PR https://github.com/bitcoinj/bitcoinj/pull/1130. Can you check if that solves your problem with Coin?

**Comment by rnicoll** [comment]
Sorry, completely forgot about this! #1130  good, thanks.

**Pull request closed without merging**
