### PR TITLE
Removed unCacheHeader method

### PR DESCRIPTION
**Pull request by BigAdam2005**
Remove unnecessary method `unCacheHeader` from `Block`

### CODE REVIEW

**Comment by schildbach** [comment]
Can you elaborate on why you think it's unnecessary?

**Comment by BigAdam2005** [comment]
It is unneeded because we can just overwrite that value without setting to null.

**Comment by schildbach** [comment]
I think it is an error to not set the `headerBytesValid` to `false` if one of the header fields changes.

Travis fails the build. Did you run the tests locally?

**Comment by BigAdam2005** [comment]
Yes and it worked.

**Pull request closed without merging**
