### PR TITLE
WalletTool: move onChange() to a Lambda

### PR DESCRIPTION
**Pull request by msgilligan**
It is a method that is only used in one place and moving this should enable
further simplification (especially replacing the CountDownLatch with a CompletableFuture see PR #3096)

See also Issue #3092

### CODE REVIEW

**Comment by msgilligan** [comment]
@schildbach Rebased fixing conflicts.

**Comment by schildbach** [comment]
I'm a bit reluctant with this because on its own I see no benefit. It introduces the "complexity" of the `Runnable` though.

**Comment by msgilligan** [comment]
> I'm a bit reluctant with this because on its own I see no benefit. It introduces the "complexity" of the `Runnable` though.

The net benefit to this PR is that the `onChange` method is removed and it is made more clear that it's really just common code for the 4 listeners. `Runnable` is pretty standard stuff. Also, by placing the `onChange` code next to the rest of the `BALANCE` case code, it makes it more obvious what is happening and invites further simplification.

But, yeah, I see your point it's not a huge benefit in-and-of-itself.

But take a look at the next step PR #3096.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
