### PR TITLE
fix number encoding in ScriptBuilder

### PR DESCRIPTION
**Pull request by thokon00**
The number 16 must be encoded with smallNum().

### CODE REVIEW

**Comment by schildbach** [comment]
Good catch! Do you think you could add a test case?

**Comment by thokon00** [comment]
Should I squash?

**Comment by thokon00** [comment]
Squashed.

**Comment by schildbach** [comment]
Thanks, merged! I moved to your testcase to ScriptTest because there already are some similar tests there.

**Pull request closed without merging**
