### PR TITLE
upgrade bouncycastle to release 1.61

### PR DESCRIPTION
**Pull request by matthewleon**
release notes: https://www.bouncycastle.org/releasenotes.html

The changes don't seem to touch any of the functionality used here.

### CODE REVIEW

**Comment by schildbach** [comment]
I tried this already a while ago, but it seems to use a Java9 method, preventing it to run on Android.

**Comment by matthewleon** [comment]
Wow. That's awful. Any recollection of what that method was? I could go digging around.

Is there anything that can be done as part of the build to signal issues like that?

**Comment by schildbach** [comment]
The message is

```
Reading program jar [/home/aschildbach/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.61/df4b474e71be02c1349c3292d98886f888d1f7/bcprov-jdk15on-1.61.jar] (filtered)
Warning: Exception while processing task java.io.IOException: Can't read [/home/aschildbach/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.61/df4b474e71be02c1349c3292d98886f888d1f7/bcprov-jdk15on-1.61.jar(;;;;;;**.class)] (Can't process class [module-info.class] (Unsupported class version number [53.0] (maximum 52.0, Java 1.8)))
```

**Comment by schildbach** [comment]
I filed an issue [here](https://github.com/bcgit/bc-java/issues/512).

**Comment by matthewleon** [comment]
Very interesting. In theory this shouldn't happen: https://techbeacon.com/app-dev-testing/legacy-developers-guide-java-9

**Comment by matthewleon** [comment]
From the linked discussion, it looks like release 1.62 should resolve this problem. Closing.

**Pull request closed without merging**
