### PR TITLE
.travis.yml: Use Ubuntu Bionic image for building.

### PR DESCRIPTION
**Pull request by schildbach**
The Bionic image is not yet official, so this is just WIP.

### CODE REVIEW

**Comment by schildbach** [comment]
Looks like the bionic image is now out of testing, so this is ready to go.

**Comment by schildbach** [comment]
Well, sadly the bionic image doesn't seem to support Java 8…

**Comment by msgilligan** [comment]
I think you can get Java 8 on Bionic by using AdoptOpenJDK.

**Comment by Polve** [comment]
You can also use Java 8 (but also 11, 12...) using zulu packages:

http://repos.azulsystems.com/

**Pull request merged**
