### PR TITLE
Mnemonic code and passphrase normalization, expanded tests

### PR DESCRIPTION
**Pull request by dbkingsb**
Resolve issues #1361 and #10.

### CODE REVIEW

**Comment by dbkingsb** [comment]
Close / Reopen to restart build.

**Comment by erasmospunk** [comment]
@dbkingsb as this bug was present for many years, could we add a method for users to recover funds by not normalising? Also what about a detection when a password uses unsafe characters?

**Comment by schildbach** [comment]
I just merged the passphrase null check (but used checkNotNull).

**Comment by schildbach** [comment]
Perhaps recovery could happen behind the scenes, simply by checking all possible variants of the passphrase? But I doubt this affects many users.

**Comment by dbkingsb** [comment]
> Perhaps recovery could happen behind the scenes, simply by checking all possible variants of the passphrase?

We could derive seeds for the 4 variants (passphrase as-is / normalized, salt as-is / normalized), but is there a way to determine which resulting seed is the intended seed?

**Comment by erasmospunk** [comment]
@dbasch there isn't a way to know for sure. It would be nice to have a detection system if the provided password is different than the normalised form.

Maybe we could have a second ```toSeed(List<String> words, String passphrase, boolean normalise)``` and the normal method calls ```toSeed(words, passphrase, true)```?

Also we could have a utility method like ```MnemonicCode#needsNormalisation``` to check if the input data needs normalisation.

I forgot to add that [libwally](https://github.com/ElementsProject/libwally-core/blob/master/src/bip39.c#L202) does not perform any normalisation as well (it expects that the library user does it).

**Comment by dbkingsb** [comment]
I'm going to close this pull request and split this branch so that we can get tests in place for the partial merge; see pull request #1562.

**Pull request closed without merging**
