### PR TITLE
a transaction output may have multiple OP_RETURNs

### PR DESCRIPTION
**Pull request by peacekeeper**
E.g. see this:

https://testnet3.toshi.io/api/v0/transactions/f18045a1b7395a4b793bfd48d919c62d4a88ed5a0e3b7fbe0b12572b6696698a

Bitcoinj should recognize this TransactionOutput as OP_RETURN

### CODE REVIEW

**Comment by mikehearn** [comment]
It looks OK but that's not a standard OP_RETURN output, is it? Why would anyone create an output like this?

**Comment by peacekeeper** [comment]
To store more than 40 bytes in an output.. I created this output myself, using Bitcoinj. This is related to the discussions around storing arbitrary data in the blockchain, such as proof-of-existence or open assets.

Here's a discussion about this:
http://bitcoin.stackexchange.com/questions/37626/can-i-have-multiple-op-return-outputs-in-one-transaction

It sounds like it's not a "standard transaction", but it doesn't get rejected either, so I thought isOpReturn() should recognize it... But I also have to say I'm quite new to this, so not 100% sure.

**Comment by luke-jr** [comment]
Uh, nothing stops you from pushing more than 40 bytes in a single pushdata...

**Comment by peacekeeper** [comment]
Again I'm new to this, but I thought there's a well-known 40 byte limit, and therefore some people do multiple OP_RETURNs in a single output.

E.g. see here:
http://bitzuma.com/posts/op-return-and-the-future-of-bitcoin/

"The 0.9.0 release of Bitcoin Core added a new standard transaction type granting access to a previously disallowed script function, OP_RETURN. This function accepts a user-defined sequence of up to 40 bytes."

**Comment by luke-jr** [comment]
The "40 byte limit" is mere node policy, *same as the one-pushdata limit*, except the 40 bytes can actually be changed easily...

**Comment by mikehearn** [comment]
OK, this change is small and unlikely to affect anything negatively, even though it's kind of weird. Happy to merge this when github stops being DoSd.

**Comment by schildbach** [comment]
Merged, thanks!

**Pull request closed without merging**
