### PR TITLE
Replace deprecated Wallet constructor with createDeterministic()

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
Yes, I think we can remove constructor in the same commit.

And maybe do the same for the `Context` variant of the constructor?

**Comment by msgilligan** [comment]
Sure. I'll add those changes.

**Comment by msgilligan** [comment]
Both of those constructors are used to create anonymous objects in test classes. Any suggestions on how best to preserve that test functionality after removing the constructors?

**Comment by schildbach** [comment]
Reduce their visibility?

**Comment by msgilligan** [comment]
> Reduce their visibility?

`protected` would allow them to be used by subclasses including anonymous subclasses in tests. We can't use package visibility because the tests are in multiple packages currently. So `protected` would work, but the question is do we want the ability to create subclasses using this constructor to be part of the API?

Two other alternatives that I can think of are:
1. Create some kind of explicit mechanism (subclasses or a mechanism using composition rather than inheritance)
2. Use a mocking framework to get the test behavior we need

I see we're already using *EasyMock* -- I haven't used that one before, so let me see if it will do what we need if we remove those constructors.

Related question: Are we running unit tests in the Android simulator? (That isn't happening on GitLab CI, but someone might be doing it locally/manually.)

**Comment by msgilligan** [comment]
I decided that I didn't want to mess with subclasses or mocks as part of this PR and did a force-push using your idea of making the constructor `protected`. I also removed the constructor that took a `NetworkParameters` and replaced its usage with the constructor that takes `Context`. Although I changed the constructor to `protected`, I left it as `@Deprecated` -- I'm not sure if you want to remove that now.

**Comment by msgilligan** [comment]
Oops, accidentally clicked the wrong button and closed and re-opened. Sorry.

**Comment by schildbach** [comment]
I just got rid of one of the two Wallet subclasses via 8718a51c5555dd3764c11b13087ec45e431ce5bc.

The other one is more tough though.

**Comment by schildbach** [comment]
Since the remaining constructur is only there for a unit test we could use the `@VisibleForTesting` annotation?

**Comment by msgilligan** [comment]
The `@VisibleForTesting` annotation is only informative, right?

**Comment by msgilligan** [comment]
@schildbach I added `@VisibleForTesting` and rebased to `master`.

This should be ready for merging _unless_ you want to remove the `@Deprecation` now that we have made visibility `protected` and added `@VisibleForTesting`.

**Comment by schildbach** [comment]
Merged, thanks!

**Pull request closed without merging**
