### PR TITLE
Update tools submodule to JDK 11

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
I think README.md (section Technologies) should be adapted in the same PR.

Also, I wonder if we should migrate the examples to Java 11 too?

**Comment by msgilligan** [comment]
> I think README.md (section Technologies) should be adapted in the same PR.

Yes. Documentation should always be updated with the code. Thanks for catching this.

> Also, I wonder if we should migrate the examples to Java 11 too?

I think so. Want me to add it to this PR?

**Comment by schildbach** [comment]
Yes, I think this can go together, if you agree.

**Comment by schildbach** [comment]
Fair enough. Thanks for the explanation.

Merged!

**Comment by msgilligan** [comment]
??

**Comment by schildbach** [comment]
Oops (-:

**Comment by schildbach** [comment]
Merged. This time for real (-:

**Pull request closed without merging**
