### PR TITLE
Database (stores) column names/objects lower case fixes.

### PR DESCRIPTION
**Pull request by kparmar1**
Database (stores MySQL/Postgres/H2) column names/objects changed to lower case.
The issue raised was #1055

### CODE REVIEW

**Comment by traber** [comment]
It seems to work for me but presumably I did not trigger the execution of all SQL statements during my tests. This is why I also manually checked the source. In DatabaseFullPrunedBlockStore I found one left over of a camel case column name in the SQL statement provided by the INSERT_OPENOUTPUTS_SQL constant ("toAddress").

**Comment by kparmar1** [comment]
Hi, Thanks. I'll fix the one I missed.
K.

**Comment by kparmar1** [comment]
I've made the fix post Mission Impossible (Not as good as the reviews suggested but well worth a watch :-)

**Comment by schildbach** [comment]
I wonder is this backwards compatible to databases already created?

**Comment by ollekullberg** [comment]
MySQL can be case sensitive, and I saw at least one table name changing case: 

"the case sensitivity of the underlying operating system plays a part in the case sensitivity of database and table names. This means database and table names are not case sensitive in Windows, and case sensitive in most varieties of Unix." 

https://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html

**Comment by mikehearn** [comment]
lol, mysql ....

**Comment by schildbach** [comment]
I'm a bit unsure on how to deal with this PR. If column names can be case sensitive, this is a breaking change. And I can imagine a pretty nasty one.

If the "users" of the database-based block stores are ok with this change I'm happy to merge.

**Comment by kparmar1** [comment]
Unfortunately this is potentially a breaking change - for some people depending on platform. I couldn't see an easy way to make everything consistent without this happening. It's something that needs to be done however as it's just too messy using case in table/column names *inconsistently*  and I can see this becoming an even bigger issue later if not rectified (if more people start to use the DB backed stores).

I'm hoping that users understand that the fullstores are experimental and until stable some of these issues will arise.

There are other options of course. Changes are managed-upgrade paths (schema versioning) and/or provide scripts for data migrations (of course this all could be automated to a certain degree).

**Comment by schildbach** [comment]
I'm not aware of any coming enhancements. I can imagine they will be restricted to "add column" and "add table", so a version would not be strictly required.

I'll merge this for now. Migration is easy enough for existing users.

**Pull request closed without merging**
