### PR TITLE
Message hierarchy: Move `parse()` to `static read()`

### PR DESCRIPTION
**Pull request by schildbach**
This will stay draft for a longer time…

* Move parsing code from `parse()` methods to ~BitcoinSerializer~ `static read()`
* Construct `Message` instances with their parsed values only
* Remove constructors that take `payloadBytes` and/or `length`
* Remove `parse()` methods altogether

### CODE REVIEW

**Comment by schildbach** [comment]
I've rebased this on our latest work, and am starting to add commits for the `parse()` to `static read()` migration. See the last couple of commits in the commit list.

It's possible that this work uncovers other necessary refactoring steps that have to be executed first. So for now I'm keeping this as draft, but reviews welcome. Once the entire migration is complete, I'll put this up for a final review.

**Comment by schildbach** [comment]
This is 13 commits that migrate `parse()` for the various message, then one commit each to remove `BaseMessage.serializer` and `BaseMessage.parse()`.

**Review by msgilligan — APPROVED** [review]
Looks great! Congratulations, this is a milestone!

**Comment by msgilligan** [comment]
@schildbach Shouldn't this be tagged for release 0.17?

**Comment by msgilligan** [comment]
@schildbach This is merged and can be closed, right?

**Pull request closed without merging**
