### PR TITLE
Fixed behaviour of OP_0 to not NullPointerException

### PR DESCRIPTION
**Pull request by w-shackleton**
`OP_0` was throwing a `NullPointerException` when chunk.data was attempted to access inside the if statement below. Since the behaviour of `OP_0` is to push an empty array to the stack I modified the behaviour as so.

### CODE REVIEW

**Comment by schildbach** [comment]
I'm currently not confident enough in scripts to review this properly. Can anyone have a look, @TheBlueMatt maybe?

@w-shackleton It would be nice if your PR would include a test case that would fail with old code and pass with your fix applied. It's not a requirement for merging, but it would perhaps make understanding the issue easier.

**Comment by w-shackleton** [comment]
Will do.

The purpose of `OP_0` is to push an "Empty array" of bytes onto the stack. While in C++ `vector` this is unambiguous, in java this could mean `null` or `new byte[] {}`. bitcoinj uses `null` and so when the regular instruction handler tries to read the stack value length we crash.

**Comment by TheBlueMatt** [comment]
Honestly, my strong preference would be to remove all of the script execution stuff. If you want script execution functionality you should be building the consensus library for your platform and link it in... It is very unmaintained and people relying on it for consensus is rather dangerous :(. I had a patch for this a while back when I was testing the consensus library when I was working in it, it was pretty simple.

**Comment by schildbach** [comment]
I squashed your two commits and merged. Thanks for spotting and fixing this.

@TheBlueMatt I guess an JNI adapter for the consensus library would be a valuable addition to bitcoinj.

**Comment by dexX7** [comment]
> @w-shackleton: bitcoinj stores null as the data for an OP_0 and so when the interpreter tries to read its length it crashes.

Just to underline this point: actually BitcoinJ should use `new byte[] {}`, and not `null` or `new byte[] {0}`.

See also #1089.

> Since the behaviour of OP_0 is to push an empty array to the stack I modified the behaviour as so.

This seems like the right way to do.

**Comment by schildbach** [comment]
@dexX7 This PR is already merged. If you know of occurences which use the wrong representation can you submit a PR to fix it, or open an issue?

**Comment by dexX7** [comment]
@schildbach: yeah, this was just a mention, so no one gets the idea `null` may be the correct representation.

> If you know of occurences which use the wrong representation can you submit a PR to fix it, or open an issue?

Back then I tested BitcoinJ with the script unit tests of Bitcoin Core, and the failing tests I've found were all related to missing script flags, such as `DISCOURAGE_UPGRADABLE_NOPS` or `MINIMALDATA`.

Here is an older test report, which may provide an insight:

- http://bitwatch.co/uploads/reports/java-libbitcoinconsensus/149aa39248-bitcoinj/classes/co.bitwatch.libbitcoinconsensus.DataDrivenBitcoinJSpec.html

The report was generated before #1089 was merged, if I recall correctly. 

But other than that, I'm currently not aware of other wrong representations or issues. :)

**Pull request closed without merging**
