### PR TITLE
Network enum comparison changes

### PR DESCRIPTION
**Pull request by msgilligan**
This depends on PR #2472 and improves comparisons based upon `NetworkParameters`/`Network`.

Will be rebased once PR #2472 is merged.

### CODE REVIEW

**Comment by schildbach** [comment]
I prefer to keep this unmerged until we can get rid of `UnitTestParams`.

**Comment by schildbach** [comment]
When/if #2588 and #2589 are merged, this could be rebased to simplify.

**Comment by msgilligan** [comment]
> When/if #2588 and #2589 are merged, this could be rebased to simplify.

That's great! I approved both of those PRs. When they're merged, I'll rebase.

**Comment by msgilligan** [comment]
@schildbach I've rebased and force-pushed. Should be ready-to-merge.

**Comment by msgilligan** [comment]
@schildbach This one is ready to merge. (After rebase, this change is now independent of UnitTestParams)

**Comment by msgilligan** [comment]
@schildbach Rebased again (to resolve conflicts) and ready-to-merge.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
