### PR TITLE
Upgrade to JavaFX 17.0.0.1

### PR DESCRIPTION
**Pull request by msgilligan**
JavaFX 17 is an LTS release and works with JDK 11 or later.

### CODE REVIEW

**Comment by schildbach** [comment]
This seems to introduce new requirements to the version of Gradle used. I get

```
WARNING: You use Gradle 4.10.2. The minimum version supported (with some limitations) by this plugin is 5.1.  It is strongly recommended to use at least Gradle 5.6.
```

**Comment by msgilligan** [comment]
I don't think the Plug-in upgrade is strictly necessary. I'll resubmit without the plug-in upgrade.

**Comment by msgilligan** [comment]
Alternatively, we could bump `minFxGradleVersion` since this module is an optional add-on anyway.

**Comment by schildbach** [comment]
I think for now I'd prefer to only update JavaFX.

**Comment by msgilligan** [comment]
> I think for now I'd prefer to only update JavaFX.

OK, I force-pushed an update with just the JavaFX version upgrade.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
