### PR TITLE
fix an npe in decryption of non-HD KeyChainGroups

### PR DESCRIPTION
**Pull request by matthewleon**
similar to the encryption fix in https://github.com/bitcoinj/bitcoinj/pull/1754

### CODE REVIEW

**Comment by matthewleon** [comment]
Sorry, looks like this one needs more work.

**Comment by matthewleon** [comment]
Okay, this is ready now. It turns out that the ordering of operations here is very important if we want to ensure that exceptions don't screw up our keychain state.

**Comment by schildbach** [comment]
Hmm, you've hidden a critical (if what you say is right) bugfix in this PR! I've extracted the fix from your PR and merged it separately.

Can you rebase this PR on current master?

**Comment by matthewleon** [comment]
You are right about the bugfix. My apologies, I had no intention to obscure it. I'm going to rebase and take extra care not to introduce that kind of issue.

**Comment by matthewleon** [comment]
It also seems to me that as long as we _are_ careful about only mutating state at the end of these methods, then the comment `// This code must be exception safe.` is not technically correct: we can throw during attempted encryption/decryption. Only the assignments at the end can't throw. But we know that assignment is safe.

**Comment by matthewleon** [comment]
This is ready for review again. I've eliminated the comments regarding exception safety: I believe that the encryption/decryption methods called here can safely throw, since mutation only occurs after they are called.

**Comment by schildbach** [comment]
You're right about the comment at the top, but shouldn't we move the comment(s) down to the beginning of the block of code that should not throw?

**Comment by matthewleon** [comment]
I've restore comments to the sections of code that are sensitive.

**Comment by schildbach** [comment]
Perfect, thanks! I merged.

**Pull request closed without merging**
