### PR TITLE
Make Address (VersionedChecksummedBytes and subclasses) and Cloneable

### PR DESCRIPTION
**Pull request by msgilligan**
* Implement Cloneable in VersionedChecksummedBytes
* Override clone() in VersionedChecksummedBytes
* Override clone() in Address
* Add Unit test file for VersionedChecksummedBytes
* Add clone unit tests for clone for all subclasses
   of VersionedChecksummedBytes

TODO: Consider overriding clone() in DumpedPrivateKey and 
      BIP38PrivateKey

### CODE REVIEW

**Comment by msgilligan** [comment]
Dang! Sorry, I did run tests on this, but tried to remove the changes I've been working on for `Comparable` and seemed to have missed something. Stay tuned.

**Comment by msgilligan** [comment]
OK, I guess it took me 3 tries to pull out my in-progress `Comparable` work to create a standalone `Cloneable` patch. Sorry for the confusion...

**Comment by mikehearn** [comment]
Looks OK but yeah, you may as well override the others too if you need them.

**Comment by msgilligan** [comment]
I do want to verify that the sort order of `version`, `byte[]` is the same as `.toString()` as Andreas asked and hopefully write some tests to verify/demonstrate that.

So, I'd be perfectly happy to submit those changes in a separate PR.

**Comment by mikehearn** [comment]
Okie dokie. Go ahead and open a separate pull for those things, I've merged this. Thanks!

**Comment by msgilligan** [comment]
PR #311 has the changes for Comparable.

**Pull request closed without merging**
