### PR TITLE
Add hooks for altcoin support, AuxPoW support classes

### PR DESCRIPTION
**Pull request by rnicoll**
Re-opening as changes need discussion. The URI factory is a bit... verbose, as an approach, but does neatly provide space for a modified factory where applicable to an altcoin. Could alternatively parse URIs in NetworkParameters, but cautious of making those classes too long.

Thoughts?

### CODE REVIEW

**Comment by mikehearn** [comment]
Comments:

* They all look good except the AuxPoW stuff - please drop that commit. The rest can go in.
* Please match the JavaDoc style: don't bother with @returns tags because the primary doc line (first sentence) should say this clearly already and the duplication is annoying. Also don't put any text after the /**
* You seem to be adding "this." prefixes a lot where they aren't necessary. They're highlighted red by github ... could you remove them please? It looks like your IDE/tool may be excessively fond of explicitly qualifying names, what are you using?

**Comment by mikehearn** [comment]
Also I am not sure what you mean with URI factory. It might be better for your altcoin library to just provide an AltcoinURI class that is independent of BitcoinURI, if it uses URIs that are significantly different. I don't see any new factories in these commits though.

**Comment by rnicoll** [comment]
That should be all of those changes applied. Apologies, found a better solution than using a factory class, forgot to update comment.

**Comment by mikehearn** [comment]
Merged, thanks!

**Pull request closed without merging**
