### PR TITLE
Fix Tor support does not use all available HTTP seeds.

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by mikehearn** [comment]
I think this should be using a MultiplexingDiscovery, no? Otherwise each one will be queried sequentially in a blocking manner with no mixing or parallelisation.

**Comment by schildbach** [comment]
Ok, so I think I fixed it. How is this?

**Comment by mikehearn** [comment]
Right, that looks better. Did you try it out? WalletTemplate can be made to use Tor just by uncommenting a line in Main.java

**Comment by schildbach** [comment]
Yes I tried it and it appears to work. Merged.

**Comment by gary-rowe** [comment]
Just a heads up on Tor - I thought I'd add it here since it may be related. 

Recently MultiBit HD users have been sending in error reports concerning Tor connectivity issues. After investigation we upgraded to Bitcoin 0.13.2/Orchid 1.1.1 but that didn't fix the problems so we've had to (hopefully temporarily) remove Tor support.

There's more information in [MultiBit HD Issue #633](https://github.com/bitcoin-solutions/multibit-hd/issues/633) which has a general overview and various links to error reports providing earlier detail. 

Do you think this fix will address the timeout problems in 1.1.1? We'd obviously like to have Tor support back in for our 0.1.4 release (expected late September) but for 0.1.3 it has to be out pending a Bitcoinj/Orchid release.

Anything we can do to help?

**Comment by mikehearn** [comment]
It's unrelated. I've seen the "unable to download key certificates" error as well but haven't had time to investigate it yet. I probably won't for a while.

**Comment by gary-rowe** [comment]
OK, I'll copy my comment into #1064 which is more specific to the issue.

**Pull request closed without merging**
