### PR TITLE
BlockFileLoader: make stream of ByteBuffer available (with test)

### PR DESCRIPTION
**Pull request by msgilligan**
* Inner class BlockFileIterator now iterates ByteBuffer
* stream() method calls makeBlock (deserializer)
* streamBuffers() method makes raw ByteBuffer blocks available
* Add integration test streamEntireBitcoindBlockChainAsBuffers()

### CODE REVIEW

**Comment by schildbach** [comment]
I think this should be rebased.

**Comment by msgilligan** [comment]
This is rebased, but is a child of PR #3186 which should be reviewed and merged first. (The first 4 commits of this PR are also contained in PR #3186)

**Comment by msgilligan** [comment]
@schildbach re-rebased and ready-for-review.

**Comment by schildbach** [comment]
Merged, but didn't catch your rebase.

**Pull request closed without merging**
