### PR TITLE
Implement Bech32m format for v1+ witness addresses

### PR DESCRIPTION
**Pull request by schildbach**
This implements the draft of BIP350. See https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki for details.

If there are no objections, I plan to merge this when it becomes clear that the spec won't change any more.

### CODE REVIEW

**Comment by Xekyo** [comment]
Hi @schildbach,

I have been working on getting a sense how various projects and companies in the Bitcoin space are planning to approach [support for sending to Bech32m](https://en.bitcoin.it/wiki/Bech32_adoption) addresses. It seems like you're on top of it for `bitcoinj`. Do you think that this PR will be merged before Taproot activation in November?

**Comment by schildbach** [comment]
> I have been working on getting a sense how various projects and companies in the Bitcoin space are planning to approach [support for sending to Bech32m](https://en.bitcoin.it/wiki/Bech32_adoption) addresses. It seems like you're on top of it for `bitcoinj`. Do you think that this PR will be merged before Taproot activation in November?

My plan is to test this PR against some implementation that can receive on Taproot addresses (and spend from there). I'm eying at Bitcoin Core, but sadly Taproot on Testnet seems to be rejected by miners. If you have a way to do interop testing of this PR, please let me know.

To answer your question, I really hope to merge this PR and release a new major version of bitcoinj before Taproot activation.

**Comment by Xekyo** [comment]
I know that taproot transactions have been working on signet, perhaps that would work. I think it only activated recently on testnet, but I haven't looked further into it.

**Comment by ddiekroeger** [comment]
the `getWitnessVersion()` function in `SegwitAddress.java` still has a comment on line 108 saying `"Only version 0 is in use right now."` - should this comment be updated for clarity?

**Comment by schildbach** [comment]
> the `getWitnessVersion()` function in `SegwitAddress.java` still has a comment on line 108 saying `"Only version 0 is in use right now."` - should this comment be updated for clarity?

Thanks for the catch! I've changed the wording to "versions 0 and 1".

**Comment by schildbach** [comment]
This is now ready for final review. If there are no objections, I'll merge this so we can get ready to _send_ to Taproot addresses in time for Taproot activation (~Nov 2021).

**Comment by schildbach** [comment]
Merged.

**Pull request merged**
