### PR TITLE
ByteUtils: remove unused helpers

### PR DESCRIPTION
**Pull request by schildbach**
I take it we agrred to not have unused read/write helpers. So this PR removes the currently unused.

### CODE REVIEW

**Comment by schildbach** [comment]
I've milestoned this to 0.17 as a reminder to go through all the read and write helpers and remove those that are unused.

**Comment by msgilligan** [comment]
> I take it we agrred to not have unused read/write helpers. So this PR removes the currently unused.

I find that which ones were are using keeps changing. So it might make sense to wait till all the refactoring is finished before removing them.

**Comment by msgilligan** [comment]
> I take it we agrred to not have unused read/write helpers. So this PR removes the currently unused.

I find that which ones were are using keeps changing. So it might make sense to wait till all the refactoring is finished before removing them.

**Comment by schildbach** [comment]
Rebased. I think the refactoring is finished, so we can probably merge this?

**Comment by msgilligan** [comment]
I think I have some unfinished refactoring that might change which ones we need. If you don't mind waiting until a little closer to release, I would prefer that.

**Comment by schildbach** [comment]
Rebased. Ready to merge?

**Review by msgilligan — APPROVED** [review]
Let's merge this. We can make any further improvements in 0.18.

**Comment by schildbach** [comment]
Merged.

**Pull request merged**
