### PR TITLE
DRMWorkaround cleanup

### PR DESCRIPTION
**Pull request by milczarekIT**
Cleaned up DRMWorkaround class

### CODE REVIEW

**Comment by schildbach** [comment]
Thanks! Can you separate your changes? I see two aspects:

- Make the class non-instantiatable
- Improve the parameter of a log message

Ideally each of those is in a separate commit. The "trigger CI build" is superfluous however – I can trigger rebuilds for you if you want.

**Comment by milczarekIT** [comment]
I added "trigger CI build", because build randomly failed.
There are really small changes in DRMWorkaround, do we really need to split it into 2 commits?

**Comment by schildbach** [comment]
I've pushed dbc4cb1d4cf47140c792fb141eb960666522d622 as an example of how "code smells" can by handled. All occasions of the same smell (originally discovered by you) are fixed at the same time, and there is a short but meaningful commit message.

**Comment by milczarekIT** [comment]
Ok, thanks, but still some improvements can be introduced in `DRMWorkaround ` proposed in this PR.

**Comment by schildbach** [comment]
Can you rebase this PR on current master so we can see what's left?

**Pull request closed without merging**
