### PR TITLE
Peer: Simplify needToRequest set of hashes

### PR DESCRIPTION
**Pull request by msgilligan**
* Make “more immutable” by using stream/toSet
* Eliminate unnecessary use of CopyOnWriteArraySet

### CODE REVIEW

**Comment by msgilligan** [comment]
First attempt had a silly mistake (that broke tests.)  I force-pushed a corrected version immediately.

**Comment by schildbach** [comment]
Looks good!

Just to clear this up: unnecessary because it's a local variable, so there is no concurrency – right?

**Comment by msgilligan** [comment]
> Just to clear this up: unnecessary because it's a local variable, so there is no concurrency – right?

It's both a local variable and once created it's not mutated. Note that when we upgrade to JDK 11 we can replace `Collectors.toSet` with `Collectors.toUnmodifiableSet` to make the immutability more clear. There is a way to do this in JDK 8 but I think it's not worth the extra complexity because this is a local.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
