### PR TITLE
Move FakeTxBuilder from `src/test` to `src/main`

### PR DESCRIPTION
**Pull request by msgilligan**
This will allow it to be used in both core tests and integration-test or in tests for any other module.

I'm also imagining some of this functionality might get merged into the "immutable" transactions capability we plan on adding.

### CODE REVIEW

**Comment by schildbach** [comment]
I see the point of this. However, the downside of testing classes in main is they get distributed and may inadvertently get part of our API. Do we actually have any test that needs this?

> I'm also imagining some of this functionality might get merged into the "immutable" transactions capability we plan on adding.

I agree.

**Comment by msgilligan** [comment]
> the downside of testing classes in main is they get distributed and may inadvertently get part of our API.

There are three simple things we can do to protect against this:

1. Put in separate package (`org.bitcoinj.testing`) - DONE
2. Tag with `@VisibleForTesting`
3. Add comments warning against its use

The name `FakeTxBuilder` is also a fairly good warning against using it.

Alternatively, I suppose we could create another module called `test-support` (for example) and have both `core` and `integration-test` depend on it. (Personally, I think the new module would be overkill. Especially since we are planning on creating the immutable transaction building classes which hopefully largely or completely replace `FakeTxBuilder`)

> Do we actually have any test that needs this? The tests in #2441 maybe?

I believe they do, but I will double-check.

**Comment by msgilligan** [comment]
> 2. Tag with `@VisibleForTesting`
> 3. Add comments warning against its use

Updated and force-pushed.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
