### PR TITLE
remove all usages of long as Instant or Duration

### PR DESCRIPTION
**Pull request by schildbach**
I'll be extracting a bit of this PR to be merged ahead on master, and to be backported to 0.17.

### CODE REVIEW

**Comment by schildbach** [comment]
This is now a child of #3482.

**Comment by schildbach** [comment]
I hope I've caught them all. It's not easy to search for: methods using "long time"

**Review by msgilligan — APPROVED** [review]
Approved.

**Comment by schildbach** [comment]
Merged.

**Pull request merged**
