### PR TITLE
Wallet.findKeyFromPubKeyHash(): Fix ScriptType, use P2PKH.

### PR DESCRIPTION
**Pull request by oscarguindzberg**

### CODE REVIEW

**Comment by schildbach** [comment]
Great catch! Merged.

**Comment by oscarguindzberg** [comment]
Should I create another PR to merge this to https://github.com/bitcoinj/bitcoinj/tree/release-0.15 ?

**Comment by schildbach** [comment]
I will cherry-pick it for 0.15.2. Are you already using 0.15?

**Comment by oscarguindzberg** [comment]
I am working on a 0.15 migration.

**Comment by schildbach** [comment]
I've backported all bugfixes. Feel free to test current release-0.15 so we can cut a 0.15.2 soon.

**Pull request closed without merging**
