### PR TITLE
Github Actions: Re-enable windows-latest

### PR DESCRIPTION
**Pull request by msgilligan**
This is a draft PR that we can keep re-basing against `master` until all the Windows-blockers are fixed.

### CODE REVIEW

**Comment by schildbach** [comment]
I'd like to merge this one real soon, but can you rebase to master for a last check if all GitHub Actions pass?

**Comment by msgilligan** [comment]
Rebased. (the 2 PRs that fix the remaining Windows issues have also been rebased to this branch)

**Comment by schildbach** [comment]
Ok, I merged the fixes. Can you rebase this PR one last time to master? Then we should see all green, right?

**Comment by msgilligan** [comment]
Rebased to master and we're ALL GREEN on Windows! ✅

**Comment by schildbach** [comment]
Merged! Yipiieh!

**Pull request closed without merging**
