### PR TITLE
Github Actions: Add JDK 16 to matrix

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
Does the Temurin distribution already have JDK 17 LTS? If so, let's move this to 17 and merge.

**Comment by msgilligan** [comment]
> Does the Temurin distribution already have JDK 17 LTS?

Not yet. I've been watching. So far only Oracle JDK (now available for free and for direct download without any click-through junk) and Oracle OpenJDK.

When it arrives, I'll force-push and then we can merge.

**Comment by schildbach** [comment]
Btw. OpenJDK 17 is now in focal-proposed. Soon it should be available via focal-updates.

**Comment by schildbach** [comment]
Based on the discussion at #2189 I'll merge this.

**Comment by schildbach** [comment]
Merged.

**Comment by schildbach** [comment]
16 will be replaced by 17 as soon as it's available.

**Pull request closed without merging**
