### PR TITLE
Increase transaction unit test coverage

### PR DESCRIPTION
**Pull request by haxwell**
Hello all!

I am trying to learn bitcoinj in a deep, intimate type manner. So I can get a job working with it, and help save the world while enjoying what I do.

To that end, I decided to write some unit tests. Who doesn't like unit tests?? Cobertura showed me that there were a bunch of red areas in Transaction.java that could use some tests. The code I have attached to this pull request is the set of tests to cover most of those areas.

Please review my code, and let me know what changes need to be made. I hope to contribute much more!

### CODE REVIEW

**Comment by mikehearn** [comment]
Are you using Eclipse? The indentation here is really messed up. Could you fix that and then I'll take another look?

FWIW: A lot of the code in Transaction is planned to change/be removed within a few months, but it can't hurt to have some unit tests until then.

**Comment by haxwell** [comment]
@mikehearn Hey, Mike.. yes, I'm using Eclipse.. I think it was a personal mistake regarding the indentation.. I've corrected it and re-committed.

For my next batch, are there any areas that would be helpful for me to focus on? If not that, then can you tell me which areas are due for major change/removal, and I'll save them for last..

**Comment by haxwell** [comment]
@mikehearn, to which version of Java is bitcoinj written? 1.6? The Travis CI build is using 1.8.0_31 to build, but its giving me an error because of the usage of a 1.7 feature. 

I'll just correct the test in the meantime, but that version info would be good to know.

**Comment by haxwell** [comment]
A test, "testEstimatedLockTime_WhenParameterSignifiesSeconds()" is failing for Travis CI, but it is building on my box.

I thought it may have to do with new code, but I updated my fork, and I don't get the error locally. The test is checking a specific, down-to-the-millisecond, date, and I suspect the value generated for this date is different on my box, and Travis CI's environment. I will update the test with better assert criteria soon.

**Comment by mikehearn** [comment]
We target 1.6 in the "core" submodule for Android compatibility but the others use Java 8.

**Comment by mikehearn** [comment]
BTW the indentation is still wrong in many places. If you click the "Files changed" tab in github you can see what I mean.

I strongly suggest avoiding Eclipse. For some reason code written by Eclipse users looks like this very often. I don't know why but Eclipse just has pathological problems with tabs vs spaces to the extent that it corrupts entire code bases. IntelliJ Community Edition is free, open source and doesn't seem to have the same issue.

**Comment by schildbach** [comment]
There is nothing wrong with Eclipse in that regard. The issue is we don't have a common code format that we can just all use.

**Comment by mikehearn** [comment]
The common code format is quite clear, I think - it's what the existing code base uses (4 space indentation). I don't know why Eclipse can't work properly with that, but it clearly doesn't, which is why the code always looks like such a mess.

**Comment by schildbach** [comment]
There is no such "quite clear format, look at existing code base" in Eclipse, and I doubt any other IDE has such a magical code format. Eclipse has like 3 predefined formats, and if you wish to customize you have plenty of possibility to do so.

**Comment by schildbach** [comment]
Most code that comes from Eclipse doesn't look like a mess. The problem must lie elsewhere.

**Comment by bumi** [comment]
It took me also a while to find how to configure my Eclipse for this. (especially since I'm used to vim for all my non java projects)
Project -> Properties -> Java Code Style -> Formatter -> Edit. 
I do have a enabled a project specific setting. Most important is the tab policy set to `spaces only` with an indentation and tab size of 4. 
When you change these settings, I think you have to touch every file again for Eclipse to update the the file.
hope this helps.

**Comment by mikehearn** [comment]
I think most editors can auto-detect the indentation settings: emacs can, Subline can, IntelliJ can since v14 too:

http://blog.jetbrains.com/idea/2014/10/intellij-idea-14-will-detect-code-styles-on-the-fly/

Anyway, the issue only arises when a project doesn't use the same style as Eclipse. It only uses tabs on the lines that are edited so things end up looking randomly out of whack.

When applying code I can fix things up, but it makes it harder to review the changes.

**Comment by haxwell** [comment]
@bumi and all, Thanks! I took your suggestion. I think that'll do it! We'll see, when I next commit!

otherwise, I just took a quick look at this failing test this morning, and couldn't see an obvious error. The ball is still in my court!

**Comment by mikehearn** [comment]
If you mean testEstimatedLockTime_WhenParameterSignifiesSeconds then don't worry about  it.

If you get the formatting fixed up then I'll do the review.

**Comment by haxwell** [comment]
Ugh.. Formatting still messed up after my most recent push.. I'll work on this more tonight..

**Comment by haxwell** [comment]
Formatting should be good now. The solution seems to set Eclipse to use _spaces only_ as @bumi suggested earlier, and also to search and replace all tabs with four spaces ("    ").

**Comment by haxwell** [comment]
@mikehearn this issue is ready for your review.. Not to rush you! But there's a 'ball in their court' label on this too, and I didn't want it to sit in deadlock status, either...

**Comment by schildbach** [comment]
Formatting is ok now, except for line 89 where you added an unnecessary tab in its own line (minor). I guess Mike will not like the amount of double-newlines you used for setting things apart. My two serious comments:

- Can you not reorganize imports? Just add your additional imports at appropriate places.
- Can you squash all your commits together into one commit, which is based on master?

**Comment by haxwell** [comment]
I couldn't change the local branch that this pull request was based on, so I created another pull request, #341.

I corrected line 89, and undid the changes in the imports. And, regarding squashing all the commits together, thats #341.

Might I suggest, too, a code format enforcement tool, like checkstyle? Considering the tabs vs spaces issue, and my liberal-but-perhaps-unappreciated use of blank lines.. Could save having this same discussion with future developers. (I'd be willing to own the implementation)

**Comment by mikehearn** [comment]
Well, the code style isn't really formalised. Things like blank lines are hard to code for. Best to just look at the surrounding code and try to match that. We could perhaps use some kind of Eclipse config file that forces it to the right indentation style though - if someone can contribute that, it'd be great.

I don't tend to worry about things like imports all that much. My own commits reorganise imports pretty frequently. It's just something that languages like Java end up needing. Ideally there'd be some canonical rules about this but then again, ideally we'd be editing ASTs instead of text :)

**Pull request closed without merging**
