### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### bitcoinj/bitcoinj now has a Chat Room on Gitter

@mikehearn has just created a chat room. You can visit it here: [https://gitter.im/bitcoinj/bitcoinj](https://gitter.im/bitcoinj/bitcoinj?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/bitcoinj/bitcoinj?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by mikehearn** [comment]
Anyone got any feelings about this? My inclination is to add it and see if people like it. I'll still hang out in IRC of course.

**Comment by schildbach** [comment]
To me it looks like spam. If you try to load the user page of that bot, it times out all the time so it likely has created (hundreds of) thousands of PR to random projects.

**Comment by mikehearn** [comment]
Well it's not spam, it only creates a PR if you sign up for the service as I did.

But if nobody is gonna use the service there's no point in having the little badge.

**Comment by schildbach** [comment]
There is no incentive to go away from #bitcoinj, I'd say.

**Comment by bumi** [comment]
+1 for IRC in favor of a proprietary service. 
for easier access of the chat within the browser we could add a link to a web based IRC client:
[Visit our IRC channel](https://kiwiirc.com/client/irc.freenode.net/bitcoinj)

```
[![Visit our IRC channel](https://kiwiirc.com/buttons/irc.freenode.net/bitcoinj.png)](https://kiwiirc.com/client/irc.freenode.net/bitcoinj)
```

**Comment by mikehearn** [comment]
Hey, that's pretty nice @bumi ! I'll add it

**Pull request closed without merging**
