### PR TITLE
Remove deprecated Block::getBlockInflation()

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
The method has been marked as deprecated in this cycle (via f04401461be4e57a3ecc51e8f2d8c2d2d31276e8). Unless there is a specific reason, maybe we should keep it for the coming release?

**Comment by msgilligan** [comment]
No specific reason, we can leave it for one release, I suppose.

I could rewrite this PR to replace our internal usage of the deprecated method.

**Comment by schildbach** [comment]
> I could rewrite this PR to replace our internal usage of the deprecated method.

Sounds good.

**Comment by msgilligan** [comment]
> > I could rewrite this PR to replace our internal usage of the deprecated method.
> 
> Sounds good.

@schildbach done!

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
