### PR TITLE
GithubCI: Upgrade to Gradle 7, add JDK 16

### PR DESCRIPTION
**Pull request by msgilligan**
Also parameterize `distribution` and `gradle` to allow for adding
future special cases with the `include: ` keyword.

### CODE REVIEW

**Comment by schildbach** [comment]
I think the parameterization (without changing any versions) could be split out of this PR into a separate PR.

**Comment by msgilligan** [comment]
> I think the parameterization (without changing any versions) could be split out of this PR into a separate PR

See PR #2187

**Comment by schildbach** [comment]
I just merged the "upgrade to gradle 7" part of this one.

**Comment by msgilligan** [comment]
This PR has been replaced by:

* PR #2187
* commit 8708f08b1b8c39c0df385cc641d162f35f7dd07d
* PR #2188

**Pull request closed without merging**
