### PR TITLE
gradle.yml, graalvm.yml: update Gradle to 7.5.1

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by schildbach** [comment]
It seems all Java 17 and Java 18 based builds have issues with the Gradle update. I'm seeing:

```
java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
        at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:233)
        at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
        at org.easymock.internal.MocksControl.createMock(MocksControl.java:107)
        at org.easymock.internal.MocksControl.createMock(MocksControl.java:85)
        at org.easymock.IMocksControl.mock(IMocksControl.java:67)
        at org.easymock.EasyMock.mock(EasyMock.java:131)
        at org.easymock.EasyMock.createMock(EasyMock.java:267)
        at org.easymock.internal.Injector.createMocksForAnnotations(Injector.java:160)
        at org.easymock.internal.Injector.injectMocks(Injector.java:67)
        at org.easymock.EasyMockSupport.injectMocks(EasyMockSupport.java:608)
        at org.easymock.EasyMockRunner.withBefores(EasyMockRunner.java:49)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:319)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
        at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
        at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
        at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74
```
and
```
org.easymock.cglib.core.CodeGenerationException: java.lang.reflect.InaccessibleObjectException-->Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1b2af04e
            at app//org.easymock.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:464)
            at app//org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:339)
            at app//org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:96)
            at app//org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:94)
            at app//org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
            at java.base@17.0.4/java.util.concurrent.FutureTask.run(FutureTask.java:264)
            at app//org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
            at app//org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
            at app//org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:119)
            at app//org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:294)
            at app//org.easymock.cglib.core.KeyFactory$Generator.create(KeyFactory.java:221)
            at app//org.easymock.cglib.core.KeyFactory.create(KeyFactory.java:174)
            at app//org.easymock.cglib.core.KeyFactory.create(KeyFactory.java:153)
            at app//org.easymock.cglib.proxy.Enhancer.<clinit>(Enhancer.java:73)
            ... 45 more

            Caused by:
            java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @1b2af04e
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
                at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
                at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
                at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
                at org.easymock.cglib.core.ReflectUtils$1.run(ReflectUtils.java:61)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
                at org.easymock.cglib.core.ReflectUtils.<clinit>(ReflectUtils.java:52)
                at org.easymock.cglib.core.KeyFactory$Generator.generateClass(KeyFactory.java:243)
                at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
                at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:332)
                ... 57 more
```

**Comment by msgilligan** [comment]
> It seems all Java 17 and Java 18 based builds have issues with the Gradle update.

I've had issues, too. I haven't had a chance to investigate yet.

**Comment by schildbach** [comment]
Rebased to see if the error persists.

**Comment by msgilligan** [comment]
The rebase fixed the problem. Perhaps because of the recent upgrade (27cc40a301cf248d8f8895c219e24a1b97294833) of EasyMock?

**Comment by msgilligan** [comment]
@schildbach We should close this and merge PR #2683 instead.

**Comment by schildbach** [comment]
Agreed.

**Pull request closed without merging**
