### PR TITLE
Align TransactionOutPoint hashCode with equals contract.

### PR DESCRIPTION
**Pull request by jamespedwards42**
Copied the hashCode from UTXO for consistency.

### CODE REVIEW

**Comment by schildbach** [comment]
I think it's not needed. The hash alone should already be unique enough, I'd say.

**Comment by jamespedwards42** [comment]
What if you have two separate outpoints coming from the same transaction?

**Comment by schildbach** [comment]
Hmm thinking about it again you're right.
Who knows, maybe it would improve our problems with handling transactions with *many* outputs?

**Comment by mikehearn** [comment]
Good catch. Our equals/hashCode methods are pretty inconsistent as they were added in an ad-hoc way over time. I checked in a variant of this that uses the IntelliJ default hash code generator, which should result in better mixing.

**Pull request closed without merging**
