### PR TITLE
Remove all usage of Java Serialization

### PR DESCRIPTION
**Pull request by msgilligan**
* Remove all implementations of `Serializable`
* Remove unit tests of Java serialization

### CODE REVIEW

**Comment by schildbach** [comment]
Years ago, when we got rid of most Java serialization, I remember we agreed to keep the Monetary/Coin/Fiat triple serializable. But we could decide otherwise, I'm not opposed to the idea.

I just grepped through Bitcoind Wallet, and Coin seems to be the only class expected to implement Serializable. I guess it would be trivial to short-time persist a long instead.

**Comment by schildbach** [comment]
I just tried to get rid of Serialization in Bitcoin Wallet, but I'd need to basically re-implement Serialization there. I'm short-time persisting a `Monetary` – meaning I'd have to persist class, amount and – in case of a `Fiat` – currency code.

**Comment by msgilligan** [comment]
> I just tried to get rid of Serialization in Bitcoin Wallet, but I'd need to basically re-implement Serialization there. I'm short-time persisting a `Monetary` – meaning I'd have to persist class, amount and – in case of a `Fiat` – currency code.

We could add `serialize` and `deserialize` methods to `Monetary` (or alternatively, perhaps just to the subclasses depending upon your use case.) We would serialize to an amount and a currency code (`BTC` for Bitcoin) and provide the reverse.

Or we could change this PR to remove serialization from everything but `Monetary` and its subclasses. I'd really like to see it removed from `Coin`, though. Maybe we could leave it just in `Fiat`.

What do you think?

**Comment by msgilligan** [comment]
@schildbach rebased now that PR #2459 is merged.

**Comment by msgilligan** [comment]
To summarize the options I presented above:

1) Add `serialize` and `deserialize` methods to `Monetary`. We would serialize to an amount and a currency code (`BTC` for Bitcoin) and provide the reverse. (would not be too different from`Fiat::parseFiat`.) 

1a) Add `serialize` and `deserialize` methods to `Fiat`.

2) Remove serialization from everything except `Monetary` and its subclasses 

2a) Remove serialization from everything except `Fiat`

3) Remove serialization from `PrefixedChecksummedBytes` only.

@schildbach What would you like me to do?

**Comment by schildbach** [comment]
I managed to keep the "re-implementation" in Bitcoin Wallet quite compact, so I think it's fine for now to remove Serialization entirely. Maybe some point in future there will be a better generic serialization mechanism.

Merged.

**Pull request merged**
