### PR TITLE
Update README to reflect max Gradle of 6.9

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by msgilligan** [comment]
@schildbach I just rebased and force pushed..

**Comment by schildbach** [comment]
Merged.

**Comment by schildbach** [comment]
Actually I just noticed post-merge, isn't the core module also limited to Gradle 6.9?

**Comment by msgilligan** [comment]
> isn't the core module also limited to Gradle 6.9?

Yes, it is.

I can make a new PR for just that.

Alternatively, I was thinking it might be better to more clearly separate build requirements from runtime requirements.

**Comment by schildbach** [comment]
I've just amended the README via d351bce29377bd82c569da4e80535654e0fafcbd.

Feel free to separate the requirements in a PR.

**Pull request closed without merging**
