### PR TITLE
ForwardingService: AutoClosable, use try-with-resources

### PR DESCRIPTION
**Pull request by msgilligan**
* ForwardingService  implement AutoClosable and use try-with-resources
* Add `kit.stopAsync()` and `kit.awaitTerminated()` in `close()`.

### CODE REVIEW

**Comment by schildbach** [comment]
This looks good. Unfortunately I failed to test it. If I insert a `System.out.println()` into the start of `close()` it's never printed. I suspect IntelliJ isn't properly terminating the process. Or, of course, the auto-close mechanism doesn't work.

**Comment by msgilligan** [comment]
Yeah, I actually think auto-close is not getting triggered by IntelliJ and probably wouldn't be with a control-c, either. I think an exception must occur within the main thread while it inside the "try-with-resources" scope.

Not swelling the `InterruptedException` might do the trick.

That doesn't mean we shouldn't use `AutoCloseable` anyway as an example/best practice.

**Comment by schildbach** [comment]
Ok, so I merged. Can't hurt (-:

**Comment by msgilligan** [comment]
PR #2557 improves this a little.

**Pull request closed without merging**
