### PR TITLE
Added sqlite blockstore

### PR DESCRIPTION
**Pull request by BigAdam2005**
Added SQLiteBlockStore class for storing blocks in SQLite database

### CODE REVIEW

**Comment by BigAdam2005** [comment]
Why no one is doing something with that pr

**Comment by BigAdam2005** [comment]
@schildbach if it is working why you don't merged it ?!

**Comment by schildbach** [comment]
Sorry, this got a bit off my radar. The problem is without a unit test and without someone actually using the class no one (except you of course) knows if it is working. I was waiting until someone shares his/her experience.

**Comment by BigAdam2005** [comment]
thanks for that response, i will create unit test.

**Comment by BigAdam2005** [comment]
this is unit tests for you

**Comment by schildbach** [comment]
Thanks. Is there a reason you're not implementing `FullPrunedBlockStore` or extending `DatabaseFullPrunedBlockStore`?

Your contribution is missing the license headers. Can you add them?

**Comment by BigAdam2005** [comment]
License added. About other interface, this isn't  `FullPrunedBlockStore ` because I'm not storing `StoredUndoableBlock` and `DatabaseFullPrunedBlockStore`  would result a lot of unnecessary code.

**Pull request closed without merging**
