### PR TITLE
equals and hashcode tests for address hierarchy

### PR DESCRIPTION
**Pull request by matthewleon**
Wanted to add these as a precaution before proceeding with refactors in the address hierarchy.

### CODE REVIEW

**Comment by schildbach** [comment]
That's an interesting way to test `equals()` and `hashCode()`!

**Comment by schildbach** [comment]
I have however the problem that inside Eclipse the new tests fail with this exception:

```
java.lang.NoSuchMethodError: com.google.common.reflect.Parameter.getAnnotatedType()Ljava/lang/reflect/AnnotatedType;
	at com.google.common.testing.NullPointerTester.isNullable(NullPointerTester.java:484)
	at com.google.common.testing.ClassSanityTester.generateDummyArg(ClassSanityTester.java:667)
	at com.google.common.testing.ClassSanityTester.testEqualsUsing(ClassSanityTester.java:573)
	at com.google.common.testing.ClassSanityTester.doTestEquals(ClassSanityTester.java:311)
	at com.google.common.testing.ClassSanityTester.testEquals(ClassSanityTester.java:285)
	at org.bitcoinj.core.LegacyAddressTest.equalsAndHashCode(LegacyAddressTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

This method is missing the `-android` variants of Guava, but not in the `-jre` variants. This makes successful execution of the tests dependent on the version precedence mechansim of Gradle. It does this:

```
testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- org.bouncycastle:bcprov-jdk15on:1.60
+--- com.google.protobuf:protobuf-java:3.6.1
+--- com.google.guava:guava:27.1-android -> 27.1-jre
|    +--- com.google.guava:failureaccess:1.0.1
|    +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.5.2
|    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    +--- com.google.j2objc:j2objc-annotations:1.1
|    \--- org.codehaus.mojo:animal-sniffer-annotations:1.17
+--- com.squareup.okhttp3:okhttp:3.12.1
|    \--- com.squareup.okio:okio:1.15.0
+--- org.slf4j:slf4j-api:1.7.25
+--- net.jcip:jcip-annotations:1.0
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- org.easymock:easymock:3.2
|    +--- cglib:cglib-nodep:2.2.2
|    \--- org.objenesis:objenesis:1.3
+--- com.google.guava:guava-testlib:27.1-jre
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.checkerframework:checker-qual:2.5.2
|    +--- com.google.errorprone:error_prone_annotations:2.2.0
|    +--- com.google.j2objc:j2objc-annotations:1.1
|    +--- com.google.guava:guava:27.1-jre (*)
|    \--- junit:junit:4.12 (*)
+--- com.fasterxml.jackson.core:jackson-databind:2.5.2
|    +--- com.fasterxml.jackson.core:jackson-annotations:2.5.0
|    \--- com.fasterxml.jackson.core:jackson-core:2.5.1
+--- org.slf4j:slf4j-jdk14:1.7.25
|    \--- org.slf4j:slf4j-api:1.7.25
+--- com.h2database:h2:1.3.167
\--- org.fusesource.leveldbjni:leveldbjni-all:1.8
```

Also all the other tests are run with a different version of Guava, which may have different bugs than the version that is used in "production". Can we tolerate that? How do the tests behave inside IntelliJ?

**Comment by matthewleon** [comment]
@schildbach have switched the tests to using EqualsVerifier (https://jqno.nl/equalsverifier/). Its behavior is more documented and customizable. Hopefully this also work on your end and doesn't have the problems above.

**Comment by schildbach** [comment]
Merged, thanks!

**Pull request closed without merging**
