### PR TITLE
CoinSelector: mark as FunctionalInterface

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by schildbach** [comment]
I think it would be good to have a little bit of rationale in its commit message. What will the functional interface do in future, or how will it help?

**Comment by msgilligan** [comment]
> I think it would be good to have a little bit of rationale in its commit message. What will the functional interface do in future, or how will it help?

I'll add more to the commit message and force-push.

The `@FunctionalInterface` annotation doesn't change behavior of `CoinSelector` in any way, it just declares our intention that it be used as a functional interface and will generate compiler errors if someone changes the code so that it is no longer a SAM type. (This is similar to the `@Override` annotation.)

**Comment by msgilligan** [comment]
@schildbach commit message updated and force-pushed.

**Comment by schildbach** [comment]
Thanks! Merged.

**Pull request closed without merging**
