### PR TITLE
PeerGroup: migrate to BlockchainDownloadEventListener (breaking)

### PR DESCRIPTION
**Pull request by msgilligan**
* Deprecate `PeerDataEventListener` (aggregate of 4 listeners)
* Remove long-deprecated `AbstractPeerDataEventListener` (4 no-op listeners)
* Add `BlockchainDownloadEventListener` (aggregate of 2 listeners)
* `PeerGroup`: replace `PeerDataEventListener` with `BlockchainDownloadEventListener` (BREAKING!)
* `DownloadProgressTracker`: implement `BlockchainDownloadEventListener` instead of `AbstractPeerDataEventListener`

This is a breaking change and will require 2 simple, one-line changes in `BlockchainDownloadListener.java` 
in Bitcoin-wallet. However, it removes the long-deprecated `AbstractPeerDataEventListener` and simplifies
the listeners for Blockchain downloading. 

After another release the deprecated `PeerDataEventListener` can be removed.

### CODE REVIEW

**Comment by msgilligan** [comment]
@schildbach This is not directly related to the refactoring in walletfx, but I was looking at ways to simplify 'WalletAppKit` and I stumbled on this little bit of extra complexity in `PeerGroup`, so I thought I would try to remove it.

**Comment by schildbach** [comment]
Looks good!

**Comment by msgilligan** [comment]
Can we target this one for 0.17?

**Comment by msgilligan** [comment]
@schildbach I think people have had a chance to look at this. I also think this may help simplify some initialization code in WalletAppKit...

**Comment by msgilligan** [comment]
@schildbach rebased.

Note that if PR #2410 is merged without this PR there are 2 deprecation warnings. After merging this PR there will be only one.  This PR removes a deprecated class that is used internally and adds another deprecation that is not used internally, so the warning goes away.

**Comment by schildbach** [comment]
It's time to merge this… done!

**Pull request closed without merging**
