### PR TITLE
Clear the blockchain file (as opposed to delete it) in preparation for restore

### PR DESCRIPTION
**Pull request by oscarguindzberg**
This is an alternative solution to https://github.com/bitcoinj/bitcoinj/pull/1695

### CODE REVIEW

**Comment by schildbach** [comment]
Sounds like a good idea to me!

**Comment by schildbach** [comment]
If that solves your problem, I like it more than #1695.

**Comment by oscarguindzberg** [comment]
I just:
- Removed WalletAppKit.provideBlockStore() and modified WalletAppKit's vStore instance variable type to stress it is of SPVBlockStore type: WalletAppKit won't work with another store type. The "overridable" solution was half-way done. Overriding provideBlockStore() to return any of the other BlockStore implementations included in bitcoinj would make the system fail on restore from seed/key. 
- Rebased from master.
- Removed "[WIP]" label from the title.

**Comment by oscarguindzberg** [comment]
@schildbach don't forget about this PR :)

**Comment by schildbach** [comment]
Thanks for the reminder! I just merged.

**Pull request closed without merging**
