### PR TITLE
core: Optimize imports

### PR DESCRIPTION
**Pull request by msgilligan**
This was done with my (default, I believe) IntelliJ settings.

I think it makes sense to "optimize" imports into a canonical format to make managing changes to imports easier in future PRs. This also should eliminate all unused imports and convert all wildcard imports to individual imports. Assuming this is the "canonical" format we want, I think we should merge this PR.

Alternatively we might want to wait for some of the current in-progress PRs to get merged before doing this so we don't have to rebase them.

### CODE REVIEW

**Comment by schildbach** [comment]
It hasn't entirely expanded all wildcards. I believe this is due to the "Class count to use import with '*'" and "Names count to use static import with '*'" settings in Editor → Code style → Java → Imports.  I remember I set it to 100 manually – I will now set it to 999, just in case.

**Comment by schildbach** [comment]
I'm not afraid of merge conflicts against this change. It's super easy to resolve them.

**Comment by msgilligan** [comment]
> It hasn't entirely expanded all wildcards. I believe this is due to the "Class count to use import with *" and "Names count to use static import with *" settings in Editor → Code style → Java → Imports. I remember I set it to 100 manually – I will now set it to 999, just in case.

OK, I'll set it to 999 and push an update.

**Comment by msgilligan** [comment]
@schildbach rebased and ready to go!

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
