### PR TITLE
[master branch] Improvement on bitcoinj for managing many account number (arbitrary accout path)

### PR DESCRIPTION
**Pull request by gmagnotta**
Dear Andreas @schildbach ,

please find the new PR that replace #1329 . This contains the same changes applied to master branch, plus the space fix.

I will add tests in following days, but if you prefer to start testing by yourself, you are welcome!!!

Regards,
Giuseppe

### CODE REVIEW

**Comment by schildbach** [comment]
Great, looks good! I'll wait a bit to allow adding unit tests, but then I'll merge.

**Comment by schildbach** [comment]
@gmagnotta Just wanted to know if you'll add unit tests?

**Comment by gmagnotta** [comment]
@schildbach Hi! Currently I can't manage it. Sorry!

**Comment by schildbach** [comment]
No worries. That's fine, thanks for letting us know.

**Comment by schildbach** [comment]
I just noticed your code only seems to support watching key chains. Is that intentional?

**Pull request closed without merging**
