### PR TITLE
Wallet: remove deprecated methods

### PR DESCRIPTION
**Pull request by msgilligan**
Remove all deprecated methods except one deprecated constructor that is used in a unit test and marked as `@VisibleForTesting`. There was one other use of this constructor in `DefaultRiskAnalysisTest` that was changed to use the `createDeterministic` static factory method.

### CODE REVIEW

**Comment by msgilligan** [comment]
One test is failing:
```
org.bitcoinj.wallet.WalletTest > createBasicUpgradeToDeterministic FAILED
[391](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:391)
    java.lang.IllegalStateException: doesn't support deterministic chains
[392](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:392)
        at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
[393](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:393)
        at org.bitcoinj.wallet.KeyChainGroup.upgradeToDeterministic(KeyChainGroup.java:953)
[394](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:394)
        at org.bitcoinj.wallet.Wallet.upgradeToDeterministic(Wallet.java:744)
[395](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:395)
        at org.bitcoinj.wallet.Wallet.upgradeToDeterministic(Wallet.java:729)
[396](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:396)
        at org.bitcoinj.wallet.WalletTest.createBasicUpgradeToDeterministic(WalletTest.java:3493)
[397](https://github.com/bitcoinj/bitcoinj/pull/2340/checks#step:4:397)
```

Previously this test was called `fromKeys` but as the `fromKeys` method was deprecated, I followed the deprecation recommendation and used `createBasic` and  `importKey`.

We should either remove or change this test. @schildbach any suggestion?

**Comment by msgilligan** [comment]
@schildbach: I just removed the problematic method in a 2nd commit. I don't understand the use cases well enough to easily tell if deleting this test reduces coverage. (It seems that at a basic level everything in that test is tested elsewhere.)

**Comment by schildbach** [comment]
I wonder if we can remove the upgrade mechanism from basic to deterministic at some point. It's a pain.

Point against it: there might be old backups which only contain a basic wallet. However e.g. Bitcoin Wallet changed the backup format at about the time when deterministic wallets were introduced, so you need to likely use an old version for restoring such old backups anyway.

**Comment by schildbach** [comment]
See #2342

**Comment by schildbach** [comment]
I merged 4952c2a345cddc05cc10c231f2718ae2b76fb460 (with a slight name change), but not the removal of the test. After merging #2343, it does not fail any more.

**Pull request closed without merging**
