### PR TITLE
MonetaryFormat: replace Guava `checkedPow()` by our own `checkedPowOf10()`

### PR DESCRIPTION
**Pull request by schildbach**
Since we only need a handful, we precompute the powers and look it up in a table.

I deliberately kept this in MonetaryFormat (rather than moving it a utils class) because it's very tailored to the usecase.

### CODE REVIEW

**Comment by schildbach** [comment]
TODO: Currently, this is throwing an IllegalArgumentException rather than the previous ArithmeticException.

**Comment by schildbach** [comment]
If we decide to make this a generic util, we could precompute the powers with exponents from 0 to 18 (inclusive). That's the highest power of 10 we can store in a long.

**Comment by JAYP1255** [comment]
Nicely put

**Comment by schildbach** [comment]
Closing in favor of #2823.

**Pull request closed without merging**
