### PR TITLE
Latest protobuf-javalite and Gradle protobuf plugin

### PR DESCRIPTION
**Pull request by msgilligan**
Let's see if this helps with Issue #2309 (This is similar to PR #2314, but also updates the Protobuf Gradle Plugin)

### CODE REVIEW

**Comment by msgilligan** [comment]
The two failing tests were not Issue #2309, so maybe we should re-run this a few times?

**Comment by msgilligan** [comment]
Nope. This (alone) doesn't fix this issue: https://github.com/msgilligan/bitcoinj/runs/5441173824?check_suite_focus=true

**Comment by schildbach** [comment]
Rerunning.

**Comment by schildbach** [comment]
This run, from this PR, exhibits the issue too: https://github.com/bitcoinj/bitcoinj/runs/5446714938

**Comment by schildbach** [comment]
Of course, it doesn't hurt to update the plugin version.

**Comment by schildbach** [comment]
Merged.

**Pull request closed without merging**
