### PR TITLE
Base58 cleanup

### PR DESCRIPTION
**Pull request by amichair**
Simplified and clarified code, slight optimizations, better documentation, corrected exception type.

### CODE REVIEW

**Comment by amichair** [comment]
Build is failing due to https://github.com/bitcoinj/bitcoinj/pull/1008... hopefully that fix will be the end of these PR build failures.

**Comment by amichair** [comment]
If you're uncomfortable with changing the API (declared exception), feel free to take only the first commit and close this issue. If there are any comments about the first commit, let me know and I'll be happy to change it.

**Comment by mikehearn** [comment]
Hmm, not sure about the exception change: yes it's quite specific but as it's checked it forces the caller to consider the case where the address is invalid, which is quite a common problem as they're often typed in. @schildbach Andreas, what do you think?

**Comment by schildbach** [comment]
In terms of API compatibility it would better to at least keep the AddressFormatException, but change it's base class to IllegalArgumentException.

Generally we want to migrate away from manually transmitting addresses (via clipboard is probably the most prominent way) to protocols like BIP70, and for use in protocols I think the exception doesn't need to be checked any more.

**Comment by mikehearn** [comment]
That sounds like a reasonable solution.

**Comment by amichair** [comment]
I changed AddressFormatException to extend IllegalArgumentException, but I'm not entirely sure if this is what you meant. And what about places that should need a checked AFE exception? Or some other *FormatExceptions where neither AFE or IAE are the best choice (e.g. BIP38PrivateKey constructor)? I'm thinking maybe to revert the whole exception thing and let it be for now.

**Comment by schildbach** [comment]
Yes, our change would also affect the other subclasses of DumpedPrivateKey. And yes, the base class change is what I meant.

I think AddressFormatException should still be declared to be thrown, because they are.

I merged the base58 cleanup commit already.

**Comment by amichair** [comment]
After a discussion on #bitcoinj, two possible goals emerged for changing the exceptions:

- change AddressFormatException to extend IllegalArgumentException so that it becomes an unchecked exception, in order to reduce boilerplate code.

- rename AddressFormatException, which is used in places unrelated to addresses (base58 utility class being one of them), to something more generic like DataFormatException, in order to clean up the API. Possibly use more specific subclasses where appropriate (e.g. AddressFormatException in Address extends DFE).

These should be considered while looking at all the current usages of AFE. They can be done together or independently. Or neither. If going for a rename, it can be done before a major release where API changes are expected.

**Comment by schildbach** [comment]
@mikehearn What do you think? You already agreed to the hierarchy change but what do you think about the renaming of the exception to a more appropriate name?

About the time if the change, I think now would be the right time: we just started the 0.14 cycle.

**Comment by mikehearn** [comment]
I leave the discussion over the exception API in your capable hands - I don't have any strong opinions on this.

**Comment by mikehearn** [comment]
Any motion here? I didn't want to stall things.

**Comment by schildbach** [comment]
I've now pushed a simpler commit than this: 200f2368c65d5fd1dae8f6f7ce6307c2e09c16c4
It just changes AddressFormatException to unchecked.

This commit needs a rebase if we still want to clean up the "overly-specific" usage of AddressFormatException. Or maybe we just rename the exception and that's it?

**Comment by schildbach** [comment]
For now, I'm closing this. If there is anything left to merge, please feel free to rebase and submit as a new PR.

**Pull request closed without merging**
