### PR TITLE
Update README.md - grammar fix

### PR DESCRIPTION
**Pull request by evil-maid**

### CODE REVIEW

**Comment by msgilligan** [comment]
I think that both with and without the comma are valid grammar. I verified this at https://writer.com/grammar-checker/

But, @schildbach I'm ok with merging this if you agree. (I will admit a user named @evil-maid makes me a little nervous haha)

**Comment by msgilligan** [comment]
@schildbach Note that @evil-maid is a new account (15 hours old) and is submitting PRs with grammar fixes to open-source crypto projects, so some caution is probably advised.

**Comment by msgilligan** [comment]
> First-time contributors need a maintainer to approve running workflows.

@schildbach Be careful.

**Comment by evil-maid** [comment]
No problem, I'm fine with leaving the grammar the way it is. It does seem both can be correct.

This is a new Github account, but I'm a serious learner, and just starting out. I'm learning by reading the README's first.

**Comment by evil-maid** [comment]
That is why I have been staying away from code for now.

**Comment by evil-maid** [comment]
I can PM someone my account from my personal Github account that is several years old.

**Comment by msgilligan** [comment]
> This is a new Github account, but I'm a serious learner, and just starting out. I'm learning by reading the README's first.

I've been known to submit 1-character fixes for typos on repositories I visit, so I hear you. We'll probably pass on this one, but don't let that discourage you.

We do need to look into the "workflow approval" issue, though....

**Comment by msgilligan** [comment]
@schildbach Please read this page and double-check the project settings, we should be diligent about this: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

**Pull request closed without merging**
