### PR TITLE
ECKey: fix usage of deprecated method ASN1TaggedObject.getObject()

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by msgilligan** [comment]
Looks good to me.  (Though I really don't understand the details of ASN1)

**Review by msgilligan — APPROVED** [review]
Looks good to me.  (Though I really don't understand the details of ASN1)

**Comment by schildbach** [comment]
Thanks for the review! 

Merged.

**Comment by msgilligan** [comment]
Woohoo! We're deprecation warning free! (Well everywhere except tests...)

**Pull request closed without merging**
