### PR TITLE
Context and save

### PR DESCRIPTION
**Pull request by devrandom**
Fixes the issue at https://github.com/bitcoinj/bitcoinj/commit/50e7e14763781db9069b2d5cf93d8df4f03c31a7#diff-b865a4a76bc217a5b92752e6c820e0efR91

Bonus - strict mode for Context propagation.

### CODE REVIEW

**Comment by mikehearn** [comment]
Ouch, that's a bad bug. I did some changes similar to yours, but without losing the exception handler and min thread priority. If you rebase the first commit should be no longer needed, and I'll take the strict mode - though the TLS magic stuff is only intended to be temporary during the transition to using Context everywhere. Then we should remove it.

**Comment by devrandom** [comment]
Thank you, rebased.

**Comment by devrandom** [comment]
I experimented with turning this on.  I think the code doesn't yet pass the context in all cases, and perhaps you already knew this.

For example, when you try to commit a new transaction, it gets logged to stdout, which does a naked getConfidence() call without a context.

**Comment by mikehearn** [comment]
Yeah, the transition isn't complete. We need to move most c'tors that take NetworkParameters to taking Context instead. Then things like toString can pass Context into getConfidence() and we can remove or deprecated the no-args getConfidence method.

**Comment by mikehearn** [comment]
Thanks, this new version LGTM

**Comment by schildbach** [comment]
I squashed the commits and merged.

@devrandom Your commit comments could use more explanation. "Show thread name" isn't really useful if you read it without previous knowledge. A good way to get into the right mood is try to formulate complete sentences, along with proper punctuation.

**Pull request closed without merging**
