### PR TITLE
wallettool: Minor (IDE suggested) Java cleanup

### PR DESCRIPTION
**Pull request by msgilligan**

### CODE REVIEW

**Comment by msgilligan** [comment]
@schildbach Do you want me to break this into multiple PRs or commits?

**Comment by msgilligan** [comment]
@schildbach Do you want me to break this into multiple PRs or commits?

**Comment by msgilligan** [comment]
> @schildbach Do you want me to break this into multiple PRs or commits?

I'm assuming this is what you want and have gone ahead and made this a DRAFT. I've submitted one of the changes separately as PR #2358.

The other changes already conflict with work-in-progress in my workspace. I'll leave this one open as  a draft to make sure they are resubmitted.

**Comment by schildbach** [comment]
I think some of this is merged now. Also, #2379 seems to conflict with this, doesn't it?

**Comment by msgilligan** [comment]
> I think some of this is merged now. Also, #2379 seems to conflict with this, doesn't it?

Yes, one piece is merged (I just rebased) another is in PR #2382, and the remaining is fixed in PR #2379.

**Pull request closed without merging**
