### PR TITLE
Provide extension hooks for altcoin support

### PR DESCRIPTION
**Pull request by rnicoll**
DO NOT MERGE: This is initially for discussion only.

Currently Dogecoin support uses a complete fork of bitcoinj, which means that it's time consuming to merge updates into the fork, and any changes made are of little use to bitcoinj. I'd like to modify bitcoinj to be less Bitcoin-specific, such that a new library (altcoinj) can then be layered on top to provide Dogecoin (and potentially other) support.

This PR illustrates the sort of changes this would require - can I get feedback on how you'd feel about such changes, before I spend too much time on this?

### CODE REVIEW

**Comment by mikehearn** [comment]
That looks pretty good, yes I'd be willing to accept this change. Perhaps more stuff should move down from NetworkParameters into AbstractBitcoinNetParams. 

In general, I'm OK with changes that are relatively small and clean like these. I don't want

  if (dogeCoin) {} 

type stuff anywhere, and I don't particularly want large/complex changes that exist only for alt coins, unless it's an alt coin I'm actually enthusiastic about (so far I haven't found one). But this sort of basic abstraction and avoidance of merge conflicts is fine.

**Comment by mikehearn** [comment]
Shall we merge this, then?

**Comment by rnicoll** [comment]
There may be more parts to this later as work on extension classes continues (been tied up with other stuff), but if you're happy to merge this "as-is", avoids having a hanging PR potential clashes later.

**Comment by rnicoll** [comment]
Going to close this for now, until I can get it actually ready to merge. Struggling to find a coherent chunk of time to work on this unfortunately

**Comment by schildbach** [comment]
@rnicoll Just to let you know, I like the general idea.

**Comment by rnicoll** [comment]
@schildbach Thanks! Work continues, just closing this so if I push interim updates to Github they don't turn up in a PR.

In hindsight should have just made a new branch. Ah well!

**Comment by rnicoll** [comment]
Have had to add in AuxPoW support, as it's a bit too invasive to extend classes with. Hope that's okay. Working on BitcoinURI generation now.

**Comment by rnicoll** [comment]
Having to re-open as some of the changes need discussion. Have rebuilt URI parsing around a factory, however it's kind of verbose. The shorter but less neat alternative would be to move parsing in with the rest of NetworkParameters. Thoughts?

**Pull request closed without merging**
