### PR TITLE
MySQL Column types and a name change

### PR DESCRIPTION
**Pull request by ollekullberg**
Change a few column types so that MySQL can perform faster, and hints to the reader the actual size of the binary data. 

Also, the column "index" should be renamed since it is a keyword in some DBs. Hard to predict the effects of using keywords as column names.

### CODE REVIEW

**Comment by ollekullberg** [comment]
Oups. These 2 commits are actually one commit. Not sure how it ended up this way?

**Comment by ollekullberg** [comment]
Ok, just saw that I forgot to remove 32 on two spots, for example:

private static final String CREATE_OUTPUTS_HASH_INDEX                       = "CREATE INDEX openoutputs_hash_idx ON openoutputs (hash(32)) USING btree

Will do a new PR.

**Comment by mikehearn** [comment]
OK, closing this one then

**Comment by kparmar1** [comment]
Just a note..
It's cool that you changed the column name (index) but this does mean everyone will be forced to recreate their stores (plus potentially change their code). I suppose they should anyway (to get the benefit) but if they didn't want to this would no longer be an option.
For myself I don't really care.

**Comment by mikehearn** [comment]
Yeah I'd rather avoid that if possible. We haven't had any reports of this causing problems so far, even though I agree it'd be better to avoid it. I suspect "index" is a remarkably common column name actually given the generality of the word and concept.

**Comment by kparmar1** [comment]
FYI: I didn't change it when I refactored (deliberately) and it seemed that the only special treatment that was required was for MySQL (wasn't a big deal).

**Comment by ollekullberg** [comment]
Aha, are these tables already running in prod somewhere? It will be painful to type 'index' every time in MySQL, if it's not in prod I would change it now (before it's too late).

**Pull request closed without merging**
