### PR TITLE
remove some calls to BigDecimal#setScale where returned objects are not used

### PR DESCRIPTION
**Pull request by p-**
Hi

I found this code with no effect while using FindBugs:
- setScale is called on immutable BigDecimal
- the returned new BigDecimal is not assigned

I'm not yet sure if there's more to it.

### CODE REVIEW

**Comment by schildbach** [comment]
@mackler Do you want to take a look?

**Comment by mackler** [comment]
Will do first thing tomorrow.

**Comment by mackler** [comment]
I have reviewed the relevant code and agree that the lines in question do nothing besides use the processor.  I am concluding that it was my error to publish them and that this pull request appropriately removes them.  Thank you Peter for recognizing this problem.

**Comment by schildbach** [comment]
Merged, thanks.

**Pull request merged**
